/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "alu.v:4" *)
module alu(select, in_a, in_b, alu_out);
  (* src = "alu.v:21" *)
  wire [15:0] _000_;
  (* src = "alu.v:21" *)
  wire [15:0] _001_;
  (* src = "alu.v:23" *)
  wire [15:0] _002_;
  (* src = "alu.v:25" *)
  wire [15:0] _003_;
  wire [3:0] _004_;
  wire [1:0] _005_;
  wire [3:0] _006_;
  wire [1:0] _007_;
  wire [3:0] _008_;
  wire [1:0] _009_;
  wire [3:0] _010_;
  wire [1:0] _011_;
  wire [3:0] _012_;
  wire [1:0] _013_;
  wire [3:0] _014_;
  wire [1:0] _015_;
  wire [3:0] _016_;
  wire [1:0] _017_;
  wire [3:0] _018_;
  wire [1:0] _019_;
  wire [3:0] _020_;
  wire [1:0] _021_;
  wire [3:0] _022_;
  wire [1:0] _023_;
  wire [3:0] _024_;
  wire [1:0] _025_;
  wire [3:0] _026_;
  wire [1:0] _027_;
  wire [3:0] _028_;
  wire [1:0] _029_;
  wire [3:0] _030_;
  wire [1:0] _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire [3:0] _034_;
  wire [1:0] _035_;
  wire [7:0] _036_;
  wire [3:0] _037_;
  wire [1:0] _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire [7:0] _043_;
  wire [3:0] _044_;
  wire [1:0] _045_;
  wire [3:0] _046_;
  wire [1:0] _047_;
  wire _048_;
  wire [15:0] _049_;
  wire [2:0] _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  (* src = "alu.v:26" *)
  wire [15:0] _059_;
  wire _060_;
  (* src = "alu.v:30|alu.v:22|<techmap.v>:432" *)
  wire [127:0] _061_;
  (* src = "alu.v:30|alu.v:22|<techmap.v>:428" *)
  wire [15:0] _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "alu.v:28" *)
  wire [15:0] _070_;
  (* src = "alu.v:29" *)
  wire [15:0] _071_;
  (* src = "alu.v:24" *)
  wire [15:0] _072_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "15" *)
  wire [15:0] _073_;
  (* src = "alu.v:34|<techmap.v>:258" *)
  wire [15:0] _074_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:203" *)
  wire [15:0] _075_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _076_;
  wire [15:0] _077_;
  wire _078_;
  wire _079_;
  (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)
  wire _080_;
  (* src = "alu.v:28|<techmap.v>:102" *)
  wire [15:0] _081_;
  (* src = "alu.v:28|<techmap.v>:102" *)
  wire [15:0] _082_;
  (* src = "alu.v:28|<techmap.v>:102" *)
  wire [15:0] _083_;
  (* src = "alu.v:28|<techmap.v>:102" *)
  wire [15:0] _084_;
  (* src = "alu.v:29|<techmap.v>:102" *)
  wire [15:0] _085_;
  (* src = "alu.v:29|<techmap.v>:102" *)
  wire [15:0] _086_;
  (* src = "alu.v:29|<techmap.v>:102" *)
  wire [15:0] _087_;
  (* src = "alu.v:29|<techmap.v>:102" *)
  wire [15:0] _088_;
  (* src = "alu.v:29|<techmap.v>:102" *)
  wire [15:0] _089_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _090_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _091_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _092_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _093_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _094_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _095_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _096_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _097_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _098_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _099_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _100_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _101_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _102_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _103_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _104_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _105_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _106_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _107_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _108_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _109_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _110_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _111_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _112_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _113_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _114_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _115_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _116_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _117_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _118_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)
  wire _119_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _120_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _121_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _122_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _123_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _124_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _125_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _126_;
  (* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)
  wire _127_;
  (* src = "alu.v:34|<techmap.v>:260" *)
  wire [15:0] _128_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _129_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _130_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _131_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _132_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _133_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _134_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _135_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _136_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _137_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _138_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _139_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _140_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _141_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _142_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _143_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _144_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _145_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _146_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _147_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _148_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _149_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _150_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _151_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _152_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _153_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _154_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _155_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _156_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _157_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _158_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _159_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _160_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _161_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _162_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _163_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _164_;
  (* src = "alu.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _165_;
  (* src = "alu.v:8" *)
  output [15:0] alu_out;
  (* src = "alu.v:6" *)
  input [15:0] in_a;
  (* src = "alu.v:7" *)
  input [15:0] in_b;
  (* src = "alu.v:10" *)
  wire [15:0] res;
  (* src = "alu.v:5" *)
  input [2:0] select;
  assign _062_[15] = _047_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _047_[1];
  assign _004_[1] = _061_[46] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[62];
  assign _004_[2] = _061_[78] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[94];
  assign _004_[3] = _061_[110] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[126];
  assign _005_[0] = _004_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _004_[1];
  assign _005_[1] = _004_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _004_[3];
  assign _062_[14] = _005_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _005_[1];
  assign _006_[1] = _061_[45] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[61];
  assign _006_[2] = _061_[77] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[93];
  assign _006_[3] = _061_[109] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[125];
  assign _007_[0] = _006_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _006_[1];
  assign _007_[1] = _006_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _006_[3];
  assign _062_[13] = _007_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _007_[1];
  assign _008_[1] = _061_[44] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[60];
  assign _008_[2] = _061_[76] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[92];
  assign _008_[3] = _061_[108] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[124];
  assign _009_[0] = _008_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _008_[1];
  assign _009_[1] = _008_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _008_[3];
  assign _062_[12] = _009_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _009_[1];
  assign _010_[1] = _061_[43] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[59];
  assign _010_[2] = _061_[75] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[91];
  assign _010_[3] = _061_[107] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[123];
  assign _011_[0] = _010_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _010_[1];
  assign _011_[1] = _010_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _010_[3];
  assign _062_[11] = _011_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _011_[1];
  assign _012_[1] = _061_[42] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[58];
  assign _012_[2] = _061_[74] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[90];
  assign _012_[3] = _061_[106] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[122];
  assign _013_[0] = _012_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _012_[1];
  assign _013_[1] = _012_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _012_[3];
  assign _062_[10] = _013_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _013_[1];
  assign _014_[1] = _061_[41] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[57];
  assign _014_[2] = _061_[73] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[89];
  assign _014_[3] = _061_[105] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[121];
  assign _015_[0] = _014_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _014_[1];
  assign _015_[1] = _014_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _014_[3];
  assign _062_[9] = _015_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _015_[1];
  assign _016_[1] = _061_[40] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[56];
  assign _016_[2] = _061_[72] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[88];
  assign _016_[3] = _061_[104] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[120];
  assign _017_[0] = _016_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _016_[1];
  assign _017_[1] = _016_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _016_[3];
  assign _062_[8] = _017_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _017_[1];
  assign _018_[1] = _061_[39] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[55];
  assign _018_[2] = _061_[71] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[87];
  assign _018_[3] = _061_[103] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[119];
  assign _019_[0] = _018_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _018_[1];
  assign _019_[1] = _018_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _018_[3];
  assign _062_[7] = _019_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _019_[1];
  assign _020_[1] = _061_[38] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[54];
  assign _020_[2] = _061_[70] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[86];
  assign _020_[3] = _061_[102] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[118];
  assign _021_[0] = _020_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _020_[1];
  assign _021_[1] = _020_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _020_[3];
  assign _062_[6] = _021_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _021_[1];
  assign _022_[1] = _061_[37] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[53];
  assign _022_[2] = _061_[69] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[85];
  assign _022_[3] = _061_[101] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[117];
  assign _023_[0] = _022_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _022_[1];
  assign _023_[1] = _022_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _022_[3];
  assign _062_[5] = _023_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _023_[1];
  assign _024_[1] = _061_[36] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[52];
  assign _024_[2] = _061_[68] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[84];
  assign _024_[3] = _061_[100] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[116];
  assign _025_[0] = _024_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _024_[1];
  assign _025_[1] = _024_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _024_[3];
  assign _062_[4] = _025_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _025_[1];
  assign _026_[1] = _061_[35] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[51];
  assign _026_[2] = _061_[67] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[83];
  assign _026_[3] = _061_[99] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[115];
  assign _027_[0] = _026_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _026_[1];
  assign _027_[1] = _026_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _026_[3];
  assign _062_[3] = _027_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _027_[1];
  assign _028_[1] = _061_[34] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[50];
  assign _028_[2] = _061_[66] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[82];
  assign _028_[3] = _061_[98] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[114];
  assign _029_[0] = _028_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _028_[1];
  assign _029_[1] = _028_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _028_[3];
  assign _062_[2] = _029_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _029_[1];
  assign _030_[0] = _061_[1] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[17];
  assign _030_[1] = _061_[33] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[49];
  assign _030_[2] = _061_[65] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[81];
  assign _030_[3] = _061_[97] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[113];
  assign _031_[0] = _030_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _030_[1];
  assign _031_[1] = _030_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _030_[3];
  assign _062_[1] = _031_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _031_[1];
  assign _032_[0] = _061_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[16];
  assign _032_[1] = _061_[32] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[48];
  assign _032_[2] = _061_[64] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[80];
  assign _032_[3] = _061_[96] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[112];
  assign _033_[0] = _032_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _032_[1];
  assign _033_[1] = _032_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _032_[3];
  assign _062_[0] = _033_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _033_[1];
  assign _034_[0] = _060_ |(* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)  _063_;
  assign _034_[1] = _064_ |(* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)  _065_;
  assign _034_[2] = _066_ |(* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)  _067_;
  assign _034_[3] = _068_ |(* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)  _069_;
  assign _035_[0] = _034_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)  _034_[1];
  assign _035_[1] = _034_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)  _034_[3];
  assign _080_ = _035_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:445" *)  _035_[1];
  assign _036_[0] = _002_[0] |(* src = "alu.v:31" *)  _049_[1];
  assign _036_[1] = _049_[2] |(* src = "alu.v:31" *)  _049_[3];
  assign _036_[2] = _049_[4] |(* src = "alu.v:31" *)  _049_[5];
  assign _036_[3] = _049_[6] |(* src = "alu.v:31" *)  _049_[7];
  assign _036_[4] = _049_[8] |(* src = "alu.v:31" *)  _049_[9];
  assign _036_[5] = _049_[10] |(* src = "alu.v:31" *)  _049_[11];
  assign _036_[6] = _049_[12] |(* src = "alu.v:31" *)  _049_[13];
  assign _036_[7] = _049_[14] |(* src = "alu.v:31" *)  _049_[15];
  assign _037_[0] = _036_[0] |(* src = "alu.v:31" *)  _036_[1];
  assign _037_[1] = _036_[2] |(* src = "alu.v:31" *)  _036_[3];
  assign _037_[2] = _036_[4] |(* src = "alu.v:31" *)  _036_[5];
  assign _037_[3] = _036_[6] |(* src = "alu.v:31" *)  _036_[7];
  assign _038_[0] = _037_[0] |(* src = "alu.v:31" *)  _037_[1];
  assign _038_[1] = _037_[2] |(* src = "alu.v:31" *)  _037_[3];
  assign _051_ = _038_[0] |(* src = "alu.v:31" *)  _038_[1];
  assign _052_ = _039_ |(* src = "alu.v:30|alu.v:22" *)  _050_[2];
  assign _053_ = _040_ |(* src = "alu.v:29|alu.v:22" *)  _050_[2];
  assign _054_ = _041_ |(* src = "alu.v:28|alu.v:22" *)  _050_[2];
  assign _055_ = _042_ |(* src = "alu.v:27|alu.v:22" *)  _050_[2];
  assign _039_ = _050_[0] |(* src = "alu.v:26|alu.v:22" *)  _050_[1];
  assign _056_ = _039_ |(* src = "alu.v:26|alu.v:22" *)  select[2];
  assign _040_ = select[0] |(* src = "alu.v:25|alu.v:22" *)  _050_[1];
  assign _057_ = _040_ |(* src = "alu.v:25|alu.v:22" *)  select[2];
  assign _041_ = _050_[0] |(* src = "alu.v:24|alu.v:22" *)  select[1];
  assign _058_ = _041_ |(* src = "alu.v:24|alu.v:22" *)  select[2];
  assign _043_[0] = _076_[0] &(* src = "alu.v:34" *)  _077_[1];
  assign _043_[2] = _077_[4] &(* src = "alu.v:34" *)  _077_[5];
  assign _043_[5] = _077_[10] &(* src = "alu.v:34" *)  _077_[11];
  assign _043_[6] = _077_[12] &(* src = "alu.v:34" *)  _077_[13];
  assign _043_[7] = _077_[14] &(* src = "alu.v:34" *)  _077_[15];
  assign _044_[0] = _043_[0] &(* src = "alu.v:34" *)  _043_[1];
  assign _044_[1] = _043_[2] &(* src = "alu.v:34" *)  _043_[3];
  assign _044_[2] = _043_[4] &(* src = "alu.v:34" *)  _043_[5];
  assign _044_[3] = _043_[6] &(* src = "alu.v:34" *)  _043_[7];
  assign _045_[0] = _044_[0] &(* src = "alu.v:34" *)  _044_[1];
  assign _045_[1] = _044_[2] &(* src = "alu.v:34" *)  _044_[3];
  assign _079_ = _045_[0] &(* src = "alu.v:34" *)  _045_[1];
  assign _046_[1] = _061_[47] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[63];
  assign _046_[2] = _061_[79] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[95];
  assign _046_[3] = _061_[111] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _061_[127];
  assign _047_[0] = _046_[0] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _046_[1];
  assign _047_[1] = _046_[2] |(* src = "alu.v:30|alu.v:22|<techmap.v>:441" *)  _046_[3];
  assign _042_ = select[0] |(* src = "alu.v:23|alu.v:22" *)  select[1];
  assign _048_ = _042_ |(* src = "alu.v:23|alu.v:22" *)  select[2];
  assign _060_ = ~(* src = "alu.v:30|alu.v:22" *) _052_;
  assign _063_ = ~(* src = "alu.v:29|alu.v:22" *) _053_;
  assign _064_ = ~(* src = "alu.v:28|alu.v:22" *) _054_;
  assign _065_ = ~(* src = "alu.v:27|alu.v:22" *) _055_;
  assign _066_ = ~(* src = "alu.v:26|alu.v:22" *) _056_;
  assign _067_ = ~(* src = "alu.v:25|alu.v:22" *) _057_;
  assign _068_ = ~(* src = "alu.v:24|alu.v:22" *) _058_;
  assign _069_ = ~(* src = "alu.v:23|alu.v:22" *) _048_;
  assign alu_out[0] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[0] : 1'hx;
  assign alu_out[1] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[1] : 1'hx;
  assign alu_out[2] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[2] : 1'hx;
  assign alu_out[3] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[3] : 1'hx;
  assign alu_out[4] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[4] : 1'hx;
  assign alu_out[5] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[5] : 1'hx;
  assign alu_out[6] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[6] : 1'hx;
  assign alu_out[7] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[7] : 1'hx;
  assign alu_out[8] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[8] : 1'hx;
  assign alu_out[9] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[9] : 1'hx;
  assign alu_out[10] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[10] : 1'hx;
  assign alu_out[11] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[11] : 1'hx;
  assign alu_out[12] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[12] : 1'hx;
  assign alu_out[13] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[13] : 1'hx;
  assign alu_out[14] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[14] : 1'hx;
  assign alu_out[15] = _080_ ? (* src = "alu.v:30|alu.v:22|<techmap.v>:445" *) _062_[15] : 1'hx;
  assign _001_[0] = ~(* src = "alu.v:34" *) _001_[1];
  assign _000_[0] = _051_ ? (* src = "alu.v:31" *) _001_[0] : 1'h0;
  assign _000_[1] = _051_ ? (* src = "alu.v:31" *) _001_[1] : 1'h0;
  assign _074_[0] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[0];
  assign _074_[1] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[1];
  assign _074_[2] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[2];
  assign _074_[3] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[3];
  assign _074_[4] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[4];
  assign _074_[5] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[5];
  assign _074_[6] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[6];
  assign _074_[7] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[7];
  assign _074_[8] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[8];
  assign _074_[9] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[9];
  assign _074_[10] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[10];
  assign _074_[11] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[11];
  assign _074_[12] = ~(* src = "alu.v:23|<techmap.v>:258" *) in_b[12];
  assign _074_[13] = ~(* src = "alu.v:34|<techmap.v>:258" *) in_b[13];
  assign _074_[14] = ~(* src = "alu.v:34|<techmap.v>:258" *) in_b[14];
  assign _074_[15] = ~(* src = "alu.v:34|<techmap.v>:258" *) in_b[15];
  assign _078_ = ~(* src = "alu.v:34" *) _075_[15];
  assign _059_[0] = in_a[0] |(* src = "alu.v:26" *)  in_b[0];
  assign _059_[1] = in_a[1] |(* src = "alu.v:26" *)  in_b[1];
  assign _059_[2] = in_a[2] |(* src = "alu.v:26" *)  in_b[2];
  assign _059_[3] = in_a[3] |(* src = "alu.v:26" *)  in_b[3];
  assign _059_[4] = in_a[4] |(* src = "alu.v:26" *)  in_b[4];
  assign _059_[5] = in_a[5] |(* src = "alu.v:26" *)  in_b[5];
  assign _059_[6] = in_a[6] |(* src = "alu.v:26" *)  in_b[6];
  assign _059_[7] = in_a[7] |(* src = "alu.v:26" *)  in_b[7];
  assign _059_[8] = in_a[8] |(* src = "alu.v:26" *)  in_b[8];
  assign _059_[9] = in_a[9] |(* src = "alu.v:26" *)  in_b[9];
  assign _059_[10] = in_a[10] |(* src = "alu.v:26" *)  in_b[10];
  assign _059_[11] = in_a[11] |(* src = "alu.v:26" *)  in_b[11];
  assign _059_[12] = in_a[12] |(* src = "alu.v:26" *)  in_b[12];
  assign _059_[13] = in_a[13] |(* src = "alu.v:26" *)  in_b[13];
  assign _059_[14] = in_a[14] |(* src = "alu.v:26" *)  in_b[14];
  assign _061_[112] = _002_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[113] = _002_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[114] = _002_[2] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[115] = _002_[3] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[116] = _002_[4] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[117] = _002_[5] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[118] = _002_[6] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[119] = _002_[7] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _059_[15] = in_a[15] |(* src = "alu.v:26" *)  in_b[15];
  assign _061_[120] = _002_[8] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[121] = _002_[9] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[122] = _002_[10] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[123] = _002_[11] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[124] = _002_[12] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[125] = _002_[13] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[126] = _002_[14] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[127] = _002_[15] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _069_;
  assign _061_[96] = _072_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[97] = _072_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[98] = _072_[2] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[99] = _072_[3] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[100] = _072_[4] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[101] = _072_[5] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[102] = _072_[6] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[103] = _072_[7] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[104] = _072_[8] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[105] = _072_[9] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[106] = _072_[10] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[107] = _072_[11] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[108] = _072_[12] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[109] = _072_[13] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[110] = _072_[14] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[111] = _072_[15] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _068_;
  assign _061_[80] = _003_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[81] = _003_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[82] = _003_[2] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[83] = _003_[3] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[84] = _003_[4] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[85] = _003_[5] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[86] = _003_[6] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[87] = _003_[7] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[88] = _003_[8] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[89] = _003_[9] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[90] = _003_[10] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[91] = _003_[11] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[92] = _003_[12] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[93] = _003_[13] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[94] = _003_[14] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[95] = _003_[15] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _067_;
  assign _061_[64] = _059_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[65] = _059_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[66] = _059_[2] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[67] = _059_[3] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[68] = _059_[4] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[69] = _059_[5] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[70] = _059_[6] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[71] = _059_[7] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[72] = _059_[8] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[73] = _059_[9] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[74] = _059_[10] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[75] = _059_[11] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[76] = _059_[12] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[77] = _059_[13] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[78] = _059_[14] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[79] = _059_[15] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _066_;
  assign _061_[48] = _002_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[49] = _049_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[50] = _049_[2] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[51] = _049_[3] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[52] = _049_[4] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[53] = _049_[5] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[54] = _049_[6] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[55] = _049_[7] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[56] = _049_[8] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[57] = _049_[9] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[58] = _049_[10] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[59] = _049_[11] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[60] = _049_[12] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[61] = _049_[13] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[62] = _049_[14] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[63] = _049_[15] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _065_;
  assign _061_[32] = _070_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[33] = _070_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[34] = _070_[2] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[35] = _070_[3] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[36] = _070_[4] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[37] = _070_[5] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[38] = _070_[6] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[39] = _070_[7] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[40] = _070_[8] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[41] = _070_[9] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[42] = _070_[10] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[43] = _070_[11] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[44] = _070_[12] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[45] = _070_[13] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[46] = _070_[14] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[47] = _070_[15] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _064_;
  assign _061_[16] = _071_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _061_[17] = _071_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _028_[0] = _071_[2] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _026_[0] = _071_[3] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _024_[0] = _071_[4] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _022_[0] = _071_[5] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _020_[0] = _071_[6] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _018_[0] = _071_[7] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _016_[0] = _071_[8] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _014_[0] = _071_[9] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _012_[0] = _071_[10] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _010_[0] = _071_[11] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _008_[0] = _071_[12] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _006_[0] = _071_[13] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _004_[0] = _071_[14] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _046_[0] = _071_[15] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _063_;
  assign _061_[0] = _000_[0] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _060_;
  assign _061_[1] = _000_[1] &(* src = "alu.v:30|alu.v:22|<techmap.v>:434" *)  _060_;
  assign _002_[1] = _049_[1] ^(* src = "alu.v:23|<techmap.v>:263" *)  _003_[0];
  assign _002_[2] = _049_[2] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[1];
  assign _002_[3] = _049_[3] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[2];
  assign _002_[4] = _049_[4] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[3];
  assign _002_[5] = _049_[5] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[4];
  assign _002_[6] = _049_[6] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[5];
  assign _002_[7] = _049_[7] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[6];
  assign _002_[8] = _049_[8] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[7];
  assign _002_[9] = _049_[9] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[8];
  assign _002_[10] = _049_[10] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[9];
  assign _002_[11] = _049_[11] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[10];
  assign _002_[12] = _049_[12] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[11];
  assign _002_[13] = _049_[13] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[12];
  assign _002_[14] = _049_[14] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[13];
  assign _002_[15] = _049_[15] ^(* src = "alu.v:23|<techmap.v>:263" *)  _073_[14];
  assign _002_[0] = in_a[0] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[0];
  assign _049_[1] = in_a[1] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[1];
  assign _049_[2] = in_a[2] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[2];
  assign _049_[3] = in_a[3] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[3];
  assign _049_[4] = in_a[4] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[4];
  assign _049_[5] = in_a[5] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[5];
  assign _049_[6] = in_a[6] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[6];
  assign _049_[7] = in_a[7] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[7];
  assign _049_[8] = in_a[8] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[8];
  assign _049_[9] = in_a[9] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[9];
  assign _049_[10] = in_a[10] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[10];
  assign _049_[11] = in_a[11] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[11];
  assign _049_[12] = in_a[12] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[12];
  assign _049_[13] = in_a[13] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[13];
  assign _049_[14] = in_a[14] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[14];
  assign _049_[15] = in_a[15] ^(* src = "alu.v:23|<techmap.v>:262" *)  in_b[15];
  assign _003_[0] = in_a[0] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[0];
  assign _003_[1] = in_a[1] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[1];
  assign _003_[2] = in_a[2] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[2];
  assign _003_[3] = in_a[3] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[3];
  assign _003_[4] = in_a[4] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[4];
  assign _003_[5] = in_a[5] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[5];
  assign _003_[6] = in_a[6] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[6];
  assign _003_[7] = in_a[7] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[7];
  assign _003_[8] = in_a[8] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[8];
  assign _003_[9] = in_a[9] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[9];
  assign _003_[10] = in_a[10] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[10];
  assign _003_[11] = in_a[11] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[11];
  assign _003_[12] = in_a[12] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[12];
  assign _003_[13] = in_a[13] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[13];
  assign _003_[14] = in_a[14] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[14];
  assign _003_[15] = in_a[15] &(* src = "alu.v:23|<techmap.v>:260" *)  in_b[15];
  assign _072_[0] = _076_[0] ^(* src = "alu.v:24|<techmap.v>:263" *)  1'h1;
  assign _072_[4] = _077_[4] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[3];
  assign _072_[5] = _077_[5] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[4];
  assign _072_[6] = _077_[6] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[5];
  assign _072_[7] = _077_[7] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[6];
  assign _072_[8] = _077_[8] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[7];
  assign _072_[9] = _077_[9] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[8];
  assign _072_[10] = _077_[10] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[9];
  assign _072_[11] = _077_[11] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[10];
  assign _072_[12] = _077_[12] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[11];
  assign _072_[13] = _077_[13] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[12];
  assign _072_[14] = _077_[14] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[13];
  assign _072_[15] = _077_[15] ^(* src = "alu.v:24|<techmap.v>:263" *)  _075_[14];
  assign _076_[0] = in_a[0] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[0];
  assign _077_[1] = in_a[1] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[1];
  assign _077_[2] = in_a[2] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[2];
  assign _077_[3] = in_a[3] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[3];
  assign _077_[4] = in_a[4] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[4];
  assign _077_[5] = in_a[5] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[5];
  assign _077_[6] = in_a[6] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[6];
  assign _077_[7] = in_a[7] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[7];
  assign _077_[8] = in_a[8] ^(* src = "alu.v:24|<techmap.v>:262" *)  _074_[8];
  assign _128_[7] = in_a[7] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[7];
  assign _128_[8] = in_a[8] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[8];
  assign _128_[9] = in_a[9] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[9];
  assign _128_[10] = in_a[10] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[10];
  assign _128_[11] = in_a[11] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[11];
  assign _128_[12] = in_a[12] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[12];
  assign _128_[13] = in_a[13] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[13];
  assign _128_[14] = in_a[14] &(* src = "alu.v:24|<techmap.v>:260" *)  _074_[14];
  assign _072_[1] = _077_[1] ^(* src = "alu.v:34|<techmap.v>:263" *)  _075_[0];
  assign _072_[2] = _077_[2] ^(* src = "alu.v:34|<techmap.v>:263" *)  _075_[1];
  assign _072_[3] = _077_[3] ^(* src = "alu.v:34|<techmap.v>:263" *)  _075_[2];
  assign _077_[9] = in_a[9] ^(* src = "alu.v:34|<techmap.v>:262" *)  _074_[9];
  assign _077_[10] = in_a[10] ^(* src = "alu.v:34|<techmap.v>:262" *)  _074_[10];
  assign _077_[11] = in_a[11] ^(* src = "alu.v:34|<techmap.v>:262" *)  _074_[11];
  assign _077_[12] = in_a[12] ^(* src = "alu.v:34|<techmap.v>:262" *)  _074_[12];
  assign _077_[13] = in_a[13] ^(* src = "alu.v:34|<techmap.v>:262" *)  _074_[13];
  assign _077_[14] = in_a[14] ^(* src = "alu.v:34|<techmap.v>:262" *)  _074_[14];
  assign _077_[15] = in_a[15] ^(* src = "alu.v:34|<techmap.v>:262" *)  _074_[15];
  assign _128_[0] = in_a[0] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[0];
  assign _128_[1] = in_a[1] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[1];
  assign _128_[2] = in_a[2] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[2];
  assign _128_[3] = in_a[3] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[3];
  assign _128_[4] = in_a[4] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[4];
  assign _128_[5] = in_a[5] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[5];
  assign _128_[6] = in_a[6] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[6];
  assign _128_[15] = in_a[15] &(* src = "alu.v:34|<techmap.v>:260" *)  _074_[15];
  assign _090_ = _049_[1] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _003_[0];
  assign _091_ = _049_[3] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _003_[2];
  assign _092_ = _049_[5] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _003_[4];
  assign _093_ = _049_[7] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _003_[6];
  assign _094_ = _049_[9] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _003_[8];
  assign _095_ = _049_[11] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _003_[10];
  assign _096_ = _049_[13] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _003_[12];
  assign _097_ = _101_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _073_[1];
  assign _098_ = _103_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _121_;
  assign _099_ = _105_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _123_;
  assign _100_ = _107_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _073_[3];
  assign _101_ = _049_[3] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _049_[2];
  assign _102_ = _049_[5] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _049_[4];
  assign _103_ = _049_[7] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _049_[6];
  assign _104_ = _049_[9] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _049_[8];
  assign _105_ = _049_[11] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _049_[10];
  assign _106_ = _049_[13] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _049_[12];
  assign _107_ = _103_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _102_;
  assign _108_ = _105_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:222" *)  _104_;
  assign _109_ = _108_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[7];
  assign _110_ = _102_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[3];
  assign _111_ = _104_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[7];
  assign _112_ = _106_ &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[11];
  assign _113_ = _049_[2] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[1];
  assign _114_ = _049_[4] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[3];
  assign _115_ = _049_[6] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[5];
  assign _116_ = _049_[8] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[7];
  assign _117_ = _049_[10] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[9];
  assign _118_ = _049_[12] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[11];
  assign _119_ = _049_[14] &(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _073_[13];
  assign _073_[1] = _003_[1] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _090_;
  assign _120_ = _003_[3] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _091_;
  assign _121_ = _003_[5] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _092_;
  assign _122_ = _003_[7] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _093_;
  assign _123_ = _003_[9] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _094_;
  assign _124_ = _003_[11] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _095_;
  assign _125_ = _003_[13] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _096_;
  assign _073_[3] = _120_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _097_;
  assign _126_ = _122_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _098_;
  assign _127_ = _124_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _099_;
  assign _073_[7] = _126_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:221" *)  _100_;
  assign _073_[11] = _127_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _109_;
  assign _073_[5] = _121_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _110_;
  assign _073_[9] = _123_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _111_;
  assign _073_[13] = _125_ |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _112_;
  assign _073_[2] = _003_[2] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _113_;
  assign _073_[4] = _003_[4] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _114_;
  assign _073_[6] = _003_[6] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _115_;
  assign _073_[8] = _003_[8] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _116_;
  assign _073_[10] = _003_[10] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _117_;
  assign _073_[12] = _003_[12] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _118_;
  assign _073_[14] = _003_[14] |(* src = "alu.v:23|<techmap.v>:260|<techmap.v>:229" *)  _119_;
  assign _129_ = _077_[1] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _075_[0];
  assign _130_ = _077_[3] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _128_[2];
  assign _131_ = _077_[5] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _128_[4];
  assign _132_ = _077_[7] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _128_[6];
  assign _133_ = _077_[9] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _128_[8];
  assign _134_ = _077_[11] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _128_[10];
  assign _135_ = _077_[13] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _128_[12];
  assign _136_ = _077_[15] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _128_[14];
  assign _137_ = _043_[1] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _075_[1];
  assign _138_ = _043_[3] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _156_;
  assign _139_ = _043_[5] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _158_;
  assign _140_ = _043_[7] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _160_;
  assign _141_ = _044_[1] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _075_[3];
  assign _142_ = _044_[3] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _163_;
  assign _143_ = _045_[1] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _075_[7];
  assign _043_[1] = _077_[3] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:222" *)  _077_[2];
  assign _043_[3] = _077_[7] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:222" *)  _077_[6];
  assign _043_[4] = _077_[9] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:222" *)  _077_[8];
  assign _144_ = _044_[2] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[7];
  assign _145_ = _043_[2] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[3];
  assign _146_ = _043_[4] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[7];
  assign _147_ = _043_[6] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[11];
  assign _148_ = _077_[2] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[1];
  assign _149_ = _077_[4] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[3];
  assign _151_ = _077_[8] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[7];
  assign _152_ = _077_[10] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[9];
  assign _153_ = _077_[12] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[11];
  assign _154_ = _077_[14] &(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _075_[13];
  assign _075_[0] = _128_[0] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:212" *)  _076_[0];
  assign _075_[1] = _128_[1] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _129_;
  assign _155_ = _128_[3] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _130_;
  assign _156_ = _128_[5] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _131_;
  assign _157_ = _128_[7] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _132_;
  assign _158_ = _128_[9] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _133_;
  assign _159_ = _128_[11] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _134_;
  assign _160_ = _128_[13] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _135_;
  assign _161_ = _128_[15] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _136_;
  assign _075_[3] = _155_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _137_;
  assign _162_ = _157_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _138_;
  assign _163_ = _159_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _139_;
  assign _164_ = _161_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _140_;
  assign _075_[7] = _162_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _141_;
  assign _165_ = _164_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _142_;
  assign _075_[15] = _165_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:221" *)  _143_;
  assign _075_[11] = _163_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _144_;
  assign _075_[5] = _156_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _145_;
  assign _075_[9] = _158_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _146_;
  assign _075_[13] = _160_ |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _147_;
  assign _075_[2] = _128_[2] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _148_;
  assign _075_[6] = _128_[6] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _150_;
  assign _075_[8] = _128_[8] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _151_;
  assign _075_[10] = _128_[10] |(* src = "alu.v:24|<techmap.v>:260|<techmap.v>:229" *)  _152_;
  assign _150_ = _077_[6] &(* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)  _075_[5];
  assign _075_[4] = _128_[4] |(* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)  _149_;
  assign _075_[12] = _128_[12] |(* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)  _153_;
  assign _075_[14] = _128_[14] |(* src = "alu.v:34|<techmap.v>:260|<techmap.v>:229" *)  _154_;
  assign _050_[2] = select[2] ^(* src = "alu.v:27|alu.v:22" *)  1'h1;
  assign _050_[1] = select[1] ^(* src = "alu.v:25|alu.v:22" *)  1'h1;
  assign _050_[0] = select[0] ^(* src = "alu.v:24|alu.v:22" *)  1'h1;
  assign _001_[1] = _078_ | _079_;
  assign _070_[0] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[0];
  assign _070_[1] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[1];
  assign _070_[2] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[2];
  assign _070_[3] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[3];
  assign _070_[4] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[4];
  assign _070_[5] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[5];
  assign _070_[6] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[6];
  assign _070_[7] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[7];
  assign _070_[8] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[8];
  assign _070_[9] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[9];
  assign _070_[10] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[10];
  assign _070_[11] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[11];
  assign _070_[12] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[12];
  assign _070_[13] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[13];
  assign _070_[14] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[14];
  assign _070_[15] = in_b[4] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _084_[15];
  assign _083_[0] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _082_[0];
  assign _083_[1] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _082_[1];
  assign _083_[2] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _082_[2];
  assign _083_[3] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _082_[3];
  assign _083_[4] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[0] : _082_[4];
  assign _083_[5] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[1] : _082_[5];
  assign _083_[6] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[2] : _082_[6];
  assign _083_[7] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[3] : _082_[7];
  assign _083_[8] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[4] : _082_[8];
  assign _083_[9] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[5] : _082_[9];
  assign _083_[10] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[6] : _082_[10];
  assign _083_[11] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[7] : _082_[11];
  assign _083_[12] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[8] : _082_[12];
  assign _083_[13] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[9] : _082_[13];
  assign _083_[14] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[10] : _082_[14];
  assign _083_[15] = in_b[2] ? (* src = "alu.v:28|<techmap.v>:107" *) _082_[11] : _082_[15];
  assign _084_[0] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[0];
  assign _084_[1] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[1];
  assign _084_[2] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[2];
  assign _084_[3] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[3];
  assign _084_[4] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[4];
  assign _084_[5] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[5];
  assign _084_[6] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[6];
  assign _084_[7] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _083_[7];
  assign _084_[8] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[0] : _083_[8];
  assign _084_[9] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[1] : _083_[9];
  assign _084_[10] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[2] : _083_[10];
  assign _084_[11] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[3] : _083_[11];
  assign _084_[12] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[4] : _083_[12];
  assign _084_[13] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[5] : _083_[13];
  assign _084_[14] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[6] : _083_[14];
  assign _084_[15] = in_b[3] ? (* src = "alu.v:28|<techmap.v>:107" *) _083_[7] : _083_[15];
  assign _082_[0] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _081_[0];
  assign _082_[1] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : _081_[1];
  assign _082_[2] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[0] : _081_[2];
  assign _082_[3] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[1] : _081_[3];
  assign _082_[4] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[2] : _081_[4];
  assign _082_[5] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[3] : _081_[5];
  assign _082_[6] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[4] : _081_[6];
  assign _082_[7] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[5] : _081_[7];
  assign _082_[8] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[6] : _081_[8];
  assign _082_[9] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[7] : _081_[9];
  assign _082_[10] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[8] : _081_[10];
  assign _082_[11] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[9] : _081_[11];
  assign _082_[12] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[10] : _081_[12];
  assign _082_[13] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[11] : _081_[13];
  assign _082_[14] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[12] : _081_[14];
  assign _082_[15] = in_b[1] ? (* src = "alu.v:28|<techmap.v>:107" *) _081_[13] : _081_[15];
  assign _081_[0] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) 1'h0 : in_a[0];
  assign _081_[1] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[0] : in_a[1];
  assign _081_[2] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[1] : in_a[2];
  assign _081_[3] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[2] : in_a[3];
  assign _081_[4] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[3] : in_a[4];
  assign _081_[5] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[4] : in_a[5];
  assign _081_[6] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[5] : in_a[6];
  assign _081_[7] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[6] : in_a[7];
  assign _081_[8] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[7] : in_a[8];
  assign _081_[9] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[8] : in_a[9];
  assign _081_[10] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[9] : in_a[10];
  assign _081_[11] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[10] : in_a[11];
  assign _081_[12] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[11] : in_a[12];
  assign _081_[13] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[12] : in_a[13];
  assign _081_[14] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[13] : in_a[14];
  assign _081_[15] = in_b[0] ? (* src = "alu.v:28|<techmap.v>:107" *) in_a[14] : in_a[15];
  assign _071_[0] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[0];
  assign _071_[1] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[1];
  assign _071_[2] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[2];
  assign _071_[3] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[3];
  assign _071_[4] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[4];
  assign _071_[5] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[5];
  assign _071_[6] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[6];
  assign _071_[7] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[7];
  assign _071_[8] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[8];
  assign _071_[9] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[9];
  assign _071_[10] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[10];
  assign _071_[11] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[11];
  assign _071_[12] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[12];
  assign _071_[13] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[13];
  assign _071_[14] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[14];
  assign _071_[15] = in_b[4] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _085_[15];
  assign _085_[0] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[0] : _089_[0];
  assign _085_[1] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[1] : _089_[1];
  assign _085_[2] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[2] : _089_[2];
  assign _085_[3] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[3] : _089_[3];
  assign _085_[4] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[4] : _089_[4];
  assign _085_[5] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[5] : _089_[5];
  assign _085_[6] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[6] : _089_[6];
  assign _085_[7] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) _086_[7] : _089_[7];
  assign _085_[8] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[0];
  assign _085_[9] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[1];
  assign _085_[10] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[2];
  assign _085_[11] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[3];
  assign _085_[12] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[4];
  assign _085_[13] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[5];
  assign _085_[14] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[6];
  assign _085_[15] = in_b[3] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _086_[7];
  assign _089_[0] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[4] : _088_[0];
  assign _089_[1] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[5] : _088_[1];
  assign _089_[2] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[6] : _088_[2];
  assign _089_[3] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[7] : _088_[3];
  assign _089_[4] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[8] : _088_[4];
  assign _089_[5] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[9] : _088_[5];
  assign _089_[6] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[10] : _088_[6];
  assign _089_[7] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[11] : _088_[7];
  assign _086_[0] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[12] : _088_[8];
  assign _086_[1] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[13] : _088_[9];
  assign _086_[2] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[14] : _088_[10];
  assign _086_[3] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) _088_[15] : _088_[11];
  assign _086_[4] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _088_[12];
  assign _086_[5] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _088_[13];
  assign _086_[6] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _088_[14];
  assign _086_[7] = in_b[2] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _088_[15];
  assign _088_[0] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[2] : _087_[0];
  assign _088_[1] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[3] : _087_[1];
  assign _088_[2] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[4] : _087_[2];
  assign _088_[3] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[5] : _087_[3];
  assign _088_[4] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[6] : _087_[4];
  assign _088_[5] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[7] : _087_[5];
  assign _088_[6] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[8] : _087_[6];
  assign _088_[7] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[9] : _087_[7];
  assign _088_[8] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[10] : _087_[8];
  assign _088_[9] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[11] : _087_[9];
  assign _088_[10] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[12] : _087_[10];
  assign _088_[11] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[13] : _087_[11];
  assign _088_[12] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[14] : _087_[12];
  assign _088_[13] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) _087_[15] : _087_[13];
  assign _088_[14] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _087_[14];
  assign _088_[15] = in_b[1] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : _087_[15];
  assign _087_[0] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[1] : in_a[0];
  assign _087_[1] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[2] : in_a[1];
  assign _087_[2] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[3] : in_a[2];
  assign _087_[3] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[4] : in_a[3];
  assign _087_[4] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[5] : in_a[4];
  assign _087_[5] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[6] : in_a[5];
  assign _087_[6] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[7] : in_a[6];
  assign _087_[7] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[8] : in_a[7];
  assign _087_[8] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[9] : in_a[8];
  assign _087_[9] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[10] : in_a[9];
  assign _087_[10] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[11] : in_a[10];
  assign _087_[11] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[12] : in_a[11];
  assign _087_[12] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[13] : in_a[12];
  assign _087_[13] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[14] : in_a[13];
  assign _087_[14] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) in_a[15] : in_a[14];
  assign _087_[15] = in_b[0] ? (* src = "alu.v:29|<techmap.v>:107" *) 1'h0 : in_a[15];
  assign _000_[15:2] = 14'h0000;
  assign _001_[15:2] = 14'h0000;
  assign _049_[0] = _002_[0];
  assign { _061_[31:18], _061_[15:2] } = { _046_[0], _004_[0], _006_[0], _008_[0], _010_[0], _012_[0], _014_[0], _016_[0], _018_[0], _020_[0], _022_[0], _024_[0], _026_[0], _028_[0], 14'h0000 };
  assign _073_[0] = _003_[0];
  assign _077_[0] = _076_[0];
  assign _086_[15:8] = 8'h00;
  assign _089_[15:8] = _086_[7:0];
  assign res = alu_out;
endmodule
