/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "alu.v:3" *)
module alu(select, in_a, in_b, alu_out);
  (* src = "alu.v:21" *)
  wire [15:0] _000_;
  (* src = "alu.v:23" *)
  wire [15:0] _001_;
  wire [1:0] _002_;
  wire [1:0] _003_;
  wire [1:0] _004_;
  wire [1:0] _005_;
  wire [1:0] _006_;
  wire [1:0] _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire [1:0] _016_;
  wire [1:0] _017_;
  wire [1:0] _018_;
  wire _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  (* src = "alu.v:24" *)
  wire [15:0] _024_;
  (* src = "alu.v:24|alu.v:20|<techmap.v>:432" *)
  wire [63:0] _025_;
  (* src = "alu.v:24|alu.v:20|<techmap.v>:428" *)
  wire [15:0] _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  (* src = "alu.v:22" *)
  wire [15:0] _031_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "15" *)
  wire [15:0] _032_;
  wire [15:0] _033_;
  (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *)
  wire _034_;
  (* src = "alu.v:22|<techmap.v>:258" *)
  wire [15:0] _035_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "15" *)
  wire [15:0] _036_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _037_;
  wire [15:0] _038_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _039_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _040_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _041_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _042_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _043_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _044_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _045_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _046_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _047_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _048_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _049_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _050_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _051_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _052_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _053_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _054_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _055_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _056_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _057_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _058_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _059_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _060_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _061_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _062_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _063_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _064_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _065_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _066_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _067_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _068_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _069_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _070_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _071_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _072_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _073_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _074_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _075_;
  (* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _076_;
  (* src = "alu.v:22|<techmap.v>:260" *)
  (* unused_bits = "15" *)
  wire [15:0] _077_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _078_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _079_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _080_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _081_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _082_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _083_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _084_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _085_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _086_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _087_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _088_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _089_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _090_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _091_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _092_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _093_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _094_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _095_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)
  wire _096_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _097_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _098_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _099_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _100_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _101_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _102_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _103_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _104_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _105_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _106_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)
  wire _107_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _108_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _109_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _110_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _111_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _112_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _113_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _114_;
  (* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)
  wire _115_;
  (* src = "alu.v:7" *)
  output [15:0] alu_out;
  (* src = "alu.v:5" *)
  input [15:0] in_a;
  (* src = "alu.v:6" *)
  input [15:0] in_b;
  (* src = "alu.v:9" *)
  wire [15:0] res;
  (* src = "alu.v:4" *)
  input [1:0] select;
  assign _021_ = _020_[0] |(* src = "alu.v:24|alu.v:20" *)  _020_[1];
  assign _022_ = select[0] |(* src = "alu.v:23|alu.v:20" *)  _020_[1];
  assign _023_ = _020_[0] |(* src = "alu.v:22|alu.v:20" *)  select[1];
  assign _002_[0] = _025_[13] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[29];
  assign _002_[1] = _025_[45] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[61];
  assign _026_[13] = _002_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _002_[1];
  assign _003_[0] = _025_[15] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[31];
  assign _003_[1] = _025_[47] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[63];
  assign _026_[15] = _003_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _003_[1];
  assign _004_[0] = _025_[14] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[30];
  assign _004_[1] = _025_[46] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[62];
  assign _026_[14] = _004_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _004_[1];
  assign _005_[0] = _025_[12] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[28];
  assign _005_[1] = _025_[44] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[60];
  assign _026_[12] = _005_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _005_[1];
  assign _006_[0] = _025_[11] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[27];
  assign _006_[1] = _025_[43] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[59];
  assign _026_[11] = _006_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _006_[1];
  assign _007_[0] = _025_[10] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[26];
  assign _007_[1] = _025_[42] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[58];
  assign _026_[10] = _007_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _007_[1];
  assign _008_[0] = _025_[9] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[25];
  assign _008_[1] = _025_[41] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[57];
  assign _026_[9] = _008_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _008_[1];
  assign _009_[0] = _025_[8] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[24];
  assign _009_[1] = _025_[40] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[56];
  assign _026_[8] = _009_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _009_[1];
  assign _010_[0] = _025_[7] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[23];
  assign _010_[1] = _025_[39] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[55];
  assign _026_[7] = _010_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _010_[1];
  assign _011_[0] = _025_[6] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[22];
  assign _011_[1] = _025_[38] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[54];
  assign _026_[6] = _011_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _011_[1];
  assign _012_[0] = _025_[5] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[21];
  assign _012_[1] = _025_[37] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[53];
  assign _026_[5] = _012_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _012_[1];
  assign _013_[0] = _025_[4] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[20];
  assign _013_[1] = _025_[36] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[52];
  assign _026_[4] = _013_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _013_[1];
  assign _014_[0] = _025_[3] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[19];
  assign _014_[1] = _025_[35] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[51];
  assign _026_[3] = _014_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _014_[1];
  assign _015_[0] = _025_[2] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[18];
  assign _015_[1] = _025_[34] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[50];
  assign _026_[2] = _015_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _015_[1];
  assign _016_[0] = _025_[1] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[17];
  assign _016_[1] = _025_[33] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[49];
  assign _026_[1] = _016_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _016_[1];
  assign _017_[0] = _025_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[16];
  assign _017_[1] = _025_[32] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _025_[48];
  assign _026_[0] = _017_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:441" *)  _017_[1];
  assign _018_[0] = _027_ |(* src = "alu.v:24|alu.v:20|<techmap.v>:445" *)  _028_;
  assign _018_[1] = _029_ |(* src = "alu.v:24|alu.v:20|<techmap.v>:445" *)  _030_;
  assign _034_ = _018_[0] |(* src = "alu.v:24|alu.v:20|<techmap.v>:445" *)  _018_[1];
  assign _019_ = select[0] |(* src = "alu.v:21|alu.v:20" *)  select[1];
  assign _027_ = ~(* src = "alu.v:24|alu.v:20" *) _021_;
  assign _028_ = ~(* src = "alu.v:23|alu.v:20" *) _022_;
  assign _029_ = ~(* src = "alu.v:22|alu.v:20" *) _023_;
  assign _030_ = ~(* src = "alu.v:21|alu.v:20" *) _019_;
  assign alu_out[0] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[0] : 1'hx;
  assign alu_out[1] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[1] : 1'hx;
  assign alu_out[2] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[2] : 1'hx;
  assign alu_out[3] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[3] : 1'hx;
  assign alu_out[4] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[4] : 1'hx;
  assign alu_out[5] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[5] : 1'hx;
  assign alu_out[6] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[6] : 1'hx;
  assign alu_out[7] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[7] : 1'hx;
  assign alu_out[8] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[8] : 1'hx;
  assign alu_out[9] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[9] : 1'hx;
  assign alu_out[10] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[10] : 1'hx;
  assign alu_out[11] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[11] : 1'hx;
  assign alu_out[12] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[12] : 1'hx;
  assign alu_out[13] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[13] : 1'hx;
  assign alu_out[14] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[14] : 1'hx;
  assign alu_out[15] = _034_ ? (* src = "alu.v:24|alu.v:20|<techmap.v>:445" *) _026_[15] : 1'hx;
  assign _035_[0] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[0];
  assign _035_[1] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[1];
  assign _035_[2] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[2];
  assign _035_[3] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[3];
  assign _035_[4] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[4];
  assign _035_[5] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[5];
  assign _035_[6] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[6];
  assign _035_[7] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[7];
  assign _035_[8] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[8];
  assign _035_[9] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[9];
  assign _035_[10] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[10];
  assign _035_[11] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[11];
  assign _035_[12] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[12];
  assign _035_[13] = ~(* src = "alu.v:21|<techmap.v>:258" *) in_b[13];
  assign _035_[14] = ~(* src = "alu.v:22|<techmap.v>:258" *) in_b[14];
  assign _035_[15] = ~(* src = "alu.v:22|<techmap.v>:258" *) in_b[15];
  assign _020_[1] = select[1] ^(* src = "alu.v:23|alu.v:20" *)  1'h1;
  assign _020_[0] = select[0] ^(* src = "alu.v:22|alu.v:20" *)  1'h1;
  assign _025_[48] = _000_[0] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[49] = _000_[1] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[50] = _000_[2] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[51] = _000_[3] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[52] = _000_[4] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[53] = _000_[5] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[54] = _000_[6] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[55] = _000_[7] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[56] = _000_[8] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[57] = _000_[9] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[58] = _000_[10] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[59] = _000_[11] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[60] = _000_[12] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[61] = _000_[13] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[62] = _000_[14] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[63] = _000_[15] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _030_;
  assign _025_[32] = _031_[0] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[33] = _031_[1] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[34] = _031_[2] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[35] = _031_[3] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[36] = _031_[4] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[37] = _031_[5] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[38] = _031_[6] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[39] = _031_[7] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[40] = _031_[8] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[41] = _031_[9] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[42] = _031_[10] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[43] = _031_[11] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[44] = _031_[12] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[45] = _031_[13] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[46] = _031_[14] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[47] = _031_[15] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _029_;
  assign _025_[16] = _001_[0] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[17] = _001_[1] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[18] = _001_[2] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[19] = _001_[3] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[20] = _001_[4] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[21] = _001_[5] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[22] = _001_[6] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[23] = _001_[7] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[24] = _001_[8] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[25] = _001_[9] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[26] = _001_[10] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[27] = _001_[11] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[28] = _001_[12] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[29] = _001_[13] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[30] = _001_[14] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[31] = _001_[15] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _028_;
  assign _025_[0] = _024_[0] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[1] = _024_[1] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[2] = _024_[2] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[3] = _024_[3] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[4] = _024_[4] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[5] = _024_[5] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[6] = _024_[6] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[7] = _024_[7] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[8] = _024_[8] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[9] = _024_[9] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[10] = _024_[10] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[11] = _024_[11] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[12] = _024_[12] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[13] = _024_[13] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[14] = _024_[14] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _025_[15] = _024_[15] &(* src = "alu.v:24|alu.v:20|<techmap.v>:434" *)  _027_;
  assign _001_[0] = in_a[0] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[0];
  assign _001_[1] = in_a[1] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[1];
  assign _001_[2] = in_a[2] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[2];
  assign _001_[3] = in_a[3] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[3];
  assign _001_[4] = in_a[4] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[4];
  assign _001_[5] = in_a[5] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[5];
  assign _001_[6] = in_a[6] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[6];
  assign _001_[7] = in_a[7] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[7];
  assign _001_[8] = in_a[8] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[8];
  assign _001_[9] = in_a[9] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[9];
  assign _001_[10] = in_a[10] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[10];
  assign _001_[11] = in_a[11] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[11];
  assign _001_[12] = in_a[12] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[12];
  assign _001_[13] = in_a[13] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[13];
  assign _001_[14] = in_a[14] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[14];
  assign _001_[15] = in_a[15] &(* src = "alu.v:21|<techmap.v>:260" *)  in_b[15];
  assign _000_[1] = _033_[1] ^(* src = "alu.v:21|<techmap.v>:263" *)  _001_[0];
  assign _000_[2] = _033_[2] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[1];
  assign _000_[3] = _033_[3] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[2];
  assign _000_[4] = _033_[4] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[3];
  assign _000_[5] = _033_[5] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[4];
  assign _000_[6] = _033_[6] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[5];
  assign _000_[7] = _033_[7] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[6];
  assign _000_[8] = _033_[8] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[7];
  assign _000_[9] = _033_[9] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[8];
  assign _000_[10] = _033_[10] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[9];
  assign _000_[11] = _033_[11] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[10];
  assign _000_[12] = _033_[12] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[11];
  assign _000_[13] = _033_[13] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[12];
  assign _000_[14] = _033_[14] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[13];
  assign _000_[15] = _033_[15] ^(* src = "alu.v:21|<techmap.v>:263" *)  _032_[14];
  assign _000_[0] = in_a[0] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[0];
  assign _033_[1] = in_a[1] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[1];
  assign _033_[2] = in_a[2] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[2];
  assign _033_[3] = in_a[3] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[3];
  assign _033_[4] = in_a[4] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[4];
  assign _033_[5] = in_a[5] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[5];
  assign _033_[6] = in_a[6] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[6];
  assign _033_[7] = in_a[7] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[7];
  assign _033_[8] = in_a[8] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[8];
  assign _033_[9] = in_a[9] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[9];
  assign _033_[10] = in_a[10] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[10];
  assign _033_[11] = in_a[11] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[11];
  assign _033_[12] = in_a[12] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[12];
  assign _033_[13] = in_a[13] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[13];
  assign _033_[14] = in_a[14] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[14];
  assign _033_[15] = in_a[15] ^(* src = "alu.v:21|<techmap.v>:262" *)  in_b[15];
  assign _077_[0] = in_a[0] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[0];
  assign _077_[1] = in_a[1] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[1];
  assign _077_[2] = in_a[2] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[2];
  assign _077_[3] = in_a[3] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[3];
  assign _077_[4] = in_a[4] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[4];
  assign _077_[5] = in_a[5] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[5];
  assign _077_[6] = in_a[6] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[6];
  assign _077_[7] = in_a[7] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[7];
  assign _077_[8] = in_a[8] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[8];
  assign _077_[9] = in_a[9] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[9];
  assign _077_[10] = in_a[10] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[10];
  assign _077_[11] = in_a[11] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[11];
  assign _077_[12] = in_a[12] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[12];
  assign _077_[13] = in_a[13] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[13];
  assign _077_[14] = in_a[14] &(* src = "alu.v:22|<techmap.v>:260" *)  _035_[14];
  assign _031_[0] = _037_[0] ^(* src = "alu.v:22|<techmap.v>:263" *)  1'h1;
  assign _031_[1] = _038_[1] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[0];
  assign _031_[2] = _038_[2] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[1];
  assign _031_[3] = _038_[3] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[2];
  assign _031_[4] = _038_[4] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[3];
  assign _031_[5] = _038_[5] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[4];
  assign _031_[6] = _038_[6] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[5];
  assign _031_[7] = _038_[7] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[6];
  assign _031_[8] = _038_[8] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[7];
  assign _031_[9] = _038_[9] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[8];
  assign _031_[10] = _038_[10] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[9];
  assign _031_[11] = _038_[11] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[10];
  assign _031_[12] = _038_[12] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[11];
  assign _031_[13] = _038_[13] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[12];
  assign _031_[14] = _038_[14] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[13];
  assign _031_[15] = _038_[15] ^(* src = "alu.v:22|<techmap.v>:263" *)  _036_[14];
  assign _037_[0] = in_a[0] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[0];
  assign _038_[1] = in_a[1] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[1];
  assign _038_[2] = in_a[2] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[2];
  assign _038_[3] = in_a[3] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[3];
  assign _038_[4] = in_a[4] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[4];
  assign _038_[5] = in_a[5] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[5];
  assign _038_[6] = in_a[6] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[6];
  assign _038_[7] = in_a[7] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[7];
  assign _038_[8] = in_a[8] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[8];
  assign _038_[9] = in_a[9] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[9];
  assign _038_[10] = in_a[10] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[10];
  assign _038_[11] = in_a[11] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[11];
  assign _038_[12] = in_a[12] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[12];
  assign _038_[13] = in_a[13] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[13];
  assign _038_[14] = in_a[14] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[14];
  assign _038_[15] = in_a[15] ^(* src = "alu.v:22|<techmap.v>:262" *)  _035_[15];
  assign _039_ = _033_[1] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[0];
  assign _040_ = _033_[3] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[2];
  assign _041_ = _033_[5] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[4];
  assign _042_ = _033_[7] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[6];
  assign _043_ = _033_[9] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[8];
  assign _044_ = _033_[11] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[10];
  assign _045_ = _033_[13] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[12];
  assign _046_ = _050_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _032_[1];
  assign _047_ = _052_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _070_;
  assign _048_ = _054_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _072_;
  assign _049_ = _056_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _032_[3];
  assign _050_ = _033_[3] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _033_[2];
  assign _051_ = _033_[5] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _033_[4];
  assign _052_ = _033_[7] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _033_[6];
  assign _053_ = _033_[9] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _033_[8];
  assign _054_ = _033_[11] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _033_[10];
  assign _055_ = _033_[13] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _033_[12];
  assign _056_ = _052_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _051_;
  assign _057_ = _054_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:222" *)  _053_;
  assign _058_ = _057_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[7];
  assign _059_ = _051_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[3];
  assign _060_ = _053_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[7];
  assign _061_ = _055_ &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[11];
  assign _062_ = _033_[2] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[1];
  assign _063_ = _033_[4] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[3];
  assign _064_ = _033_[6] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[5];
  assign _065_ = _033_[8] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[7];
  assign _066_ = _033_[10] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[9];
  assign _067_ = _033_[12] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[11];
  assign _068_ = _033_[14] &(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _032_[13];
  assign _032_[1] = _001_[1] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _039_;
  assign _069_ = _001_[3] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _040_;
  assign _070_ = _001_[5] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _041_;
  assign _071_ = _001_[7] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _042_;
  assign _072_ = _001_[9] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _043_;
  assign _073_ = _001_[11] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _044_;
  assign _074_ = _001_[13] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _045_;
  assign _032_[3] = _069_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _046_;
  assign _075_ = _071_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _047_;
  assign _076_ = _073_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _048_;
  assign _032_[7] = _075_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:221" *)  _049_;
  assign _032_[11] = _076_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _058_;
  assign _032_[5] = _070_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _059_;
  assign _032_[9] = _072_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _060_;
  assign _032_[13] = _074_ |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _061_;
  assign _032_[2] = _001_[2] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _062_;
  assign _032_[4] = _001_[4] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _063_;
  assign _032_[6] = _001_[6] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _064_;
  assign _032_[8] = _001_[8] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _065_;
  assign _032_[10] = _001_[10] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _066_;
  assign _032_[12] = _001_[12] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _067_;
  assign _032_[14] = _001_[14] |(* src = "alu.v:21|<techmap.v>:260|<techmap.v>:229" *)  _068_;
  assign _078_ = _038_[1] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _036_[0];
  assign _079_ = _038_[3] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _077_[2];
  assign _080_ = _038_[5] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _077_[4];
  assign _081_ = _038_[7] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _077_[6];
  assign _082_ = _038_[9] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _077_[8];
  assign _083_ = _038_[11] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _077_[10];
  assign _084_ = _038_[13] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _077_[12];
  assign _085_ = _089_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _036_[1];
  assign _086_ = _091_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _109_;
  assign _087_ = _093_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _111_;
  assign _088_ = _095_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _036_[3];
  assign _089_ = _038_[3] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _038_[2];
  assign _090_ = _038_[5] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _038_[4];
  assign _091_ = _038_[7] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _038_[6];
  assign _092_ = _038_[9] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _038_[8];
  assign _093_ = _038_[11] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _038_[10];
  assign _094_ = _038_[13] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _038_[12];
  assign _095_ = _091_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _090_;
  assign _096_ = _093_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:222" *)  _092_;
  assign _097_ = _096_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[7];
  assign _098_ = _090_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[3];
  assign _099_ = _092_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[7];
  assign _100_ = _094_ &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[11];
  assign _101_ = _038_[2] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[1];
  assign _102_ = _038_[4] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[3];
  assign _103_ = _038_[6] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[5];
  assign _104_ = _038_[8] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[7];
  assign _105_ = _038_[10] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[9];
  assign _106_ = _038_[12] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[11];
  assign _107_ = _038_[14] &(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _036_[13];
  assign _036_[0] = _077_[0] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:212" *)  _037_[0];
  assign _036_[1] = _077_[1] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _078_;
  assign _108_ = _077_[3] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _079_;
  assign _109_ = _077_[5] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _080_;
  assign _110_ = _077_[7] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _081_;
  assign _111_ = _077_[9] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _082_;
  assign _112_ = _077_[11] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _083_;
  assign _113_ = _077_[13] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _084_;
  assign _036_[3] = _108_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _085_;
  assign _114_ = _110_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _086_;
  assign _115_ = _112_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _087_;
  assign _036_[7] = _114_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:221" *)  _088_;
  assign _036_[11] = _115_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _097_;
  assign _036_[5] = _109_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _098_;
  assign _036_[9] = _111_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _099_;
  assign _036_[13] = _113_ |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _100_;
  assign _036_[2] = _077_[2] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _101_;
  assign _036_[4] = _077_[4] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _102_;
  assign _036_[6] = _077_[6] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _103_;
  assign _036_[8] = _077_[8] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _104_;
  assign _036_[10] = _077_[10] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _105_;
  assign _036_[12] = _077_[12] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _106_;
  assign _036_[14] = _077_[14] |(* src = "alu.v:22|<techmap.v>:260|<techmap.v>:229" *)  _107_;
  assign _024_[0] = in_a[0] |(* src = "alu.v:24" *)  in_b[0];
  assign _024_[1] = in_a[1] |(* src = "alu.v:24" *)  in_b[1];
  assign _024_[2] = in_a[2] |(* src = "alu.v:24" *)  in_b[2];
  assign _024_[3] = in_a[3] |(* src = "alu.v:24" *)  in_b[3];
  assign _024_[4] = in_a[4] |(* src = "alu.v:24" *)  in_b[4];
  assign _024_[5] = in_a[5] |(* src = "alu.v:24" *)  in_b[5];
  assign _024_[6] = in_a[6] |(* src = "alu.v:24" *)  in_b[6];
  assign _024_[7] = in_a[7] |(* src = "alu.v:24" *)  in_b[7];
  assign _024_[8] = in_a[8] |(* src = "alu.v:24" *)  in_b[8];
  assign _024_[9] = in_a[9] |(* src = "alu.v:24" *)  in_b[9];
  assign _024_[10] = in_a[10] |(* src = "alu.v:24" *)  in_b[10];
  assign _024_[11] = in_a[11] |(* src = "alu.v:24" *)  in_b[11];
  assign _024_[12] = in_a[12] |(* src = "alu.v:24" *)  in_b[12];
  assign _024_[13] = in_a[13] |(* src = "alu.v:24" *)  in_b[13];
  assign _024_[14] = in_a[14] |(* src = "alu.v:24" *)  in_b[14];
  assign _024_[15] = in_a[15] |(* src = "alu.v:24" *)  in_b[15];
  assign _032_[0] = _001_[0];
  assign _033_[0] = _000_[0];
  assign _038_[0] = _037_[0];
  assign res = alu_out;
endmodule
