/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "bigger.v:2" *)
module bigger(clk, reset, run, done, instr, d_out);
  (* src = "bigger.v:64" *)
  wire [1:0] _00_;
  wire [1:0] _01_;
  wire [1:0] _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [1:0] _05_;
  wire [1:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "bigger.v:70" *)
  wire _10_;
  wire [1:0] _11_;
  (* src = "bigger.v:80|bigger.v:76|<techmap.v>:428" *)
  wire [1:0] _12_;
  (* src = "bigger.v:80|bigger.v:76|<techmap.v>:445" *)
  wire _13_;
  (* src = "bigger.v:23" *)
  wire [7:0] addr;
  (* src = "bigger.v:3" *)
  input clk;
  (* src = "bigger.v:19" *)
  reg [1:0] cur_state;
  (* src = "bigger.v:9" *)
  output [15:0] d_out;
  (* src = "bigger.v:7" *)
  output done;
  (* src = "bigger.v:8" *)
  output [15:0] instr;
  (* src = "bigger.v:22" *)
  wire [15:0] mem_out;
  (* src = "bigger.v:24" *)
  wire [7:0] new_pc;
  (* src = "bigger.v:19" *)
  wire [1:0] next_state;
  (* src = "bigger.v:4" *)
  input reset;
  (* src = "bigger.v:5" *)
  input run;
  (* src = "bigger.v:21" *)
  wire run_bitty;
  assign _07_ = _06_[0] |(* src = "bigger.v:58|bigger.v:54" *)  _05_[1];
  assign _12_[1] = _01_[0] |(* src = "bigger.v:80|bigger.v:76|<techmap.v>:441" *)  _01_[1];
  assign _12_[0] = _01_[0] |(* src = "bigger.v:80|bigger.v:76|<techmap.v>:441" *)  _02_[1];
  assign _03_[0] = run_bitty |(* src = "bigger.v:80|bigger.v:76|<techmap.v>:445" *)  _01_[0];
  assign _03_[1] = _01_[1] |(* src = "bigger.v:80|bigger.v:76|<techmap.v>:445" *)  _02_[1];
  assign _13_ = _03_[0] |(* src = "bigger.v:80|bigger.v:76|<techmap.v>:445" *)  _03_[1];
  assign _08_ = cur_state[0] |(* src = "bigger.v:79|bigger.v:76" *)  _05_[1];
  assign _09_ = _06_[0] |(* src = "bigger.v:78|bigger.v:76" *)  cur_state[1];
  assign _04_ = cur_state[0] |(* src = "bigger.v:77|bigger.v:76" *)  cur_state[1];
  assign _01_[0] = ~(* src = "bigger.v:79|bigger.v:76" *) _08_;
  assign _01_[1] = ~(* src = "bigger.v:78|bigger.v:76" *) _09_;
  assign _02_[1] = ~(* src = "bigger.v:77|bigger.v:76" *) _04_;
  assign _10_ = reset |(* src = "bigger.v:70" *)  done;
  assign run_bitty = ~(* src = "bigger.v:58|bigger.v:54" *) _07_;
  assign next_state[0] = _13_ ? (* src = "bigger.v:80|bigger.v:76|<techmap.v>:445" *) _12_[0] : 1'hx;
  assign next_state[1] = _13_ ? (* src = "bigger.v:80|bigger.v:76|<techmap.v>:445" *) _12_[1] : 1'hx;
  assign _11_[0] = run ? (* src = "bigger.v:65" *) next_state[0] : cur_state[0];
  assign _11_[1] = run ? (* src = "bigger.v:65" *) next_state[1] : cur_state[1];
  assign _00_[0] = _10_ ? (* src = "bigger.v:70" *) 1'h0 : _11_[0];
  assign _00_[1] = _10_ ? (* src = "bigger.v:70" *) 1'h0 : _11_[1];
  (* src = "bigger.v:64" *)
  always @(posedge clk)
      cur_state[0] <= _00_[0];
  (* src = "bigger.v:64" *)
  always @(posedge clk)
      cur_state[1] <= _00_[1];
  assign _05_[1] = cur_state[1] ^(* src = "bigger.v:58|bigger.v:54" *)  1'h1;
  assign _06_[0] = cur_state[0] ^(* src = "bigger.v:78|bigger.v:76" *)  1'h1;
  (* module_not_derived = 32'd1 *)
  (* src = "bigger.v:35" *)
  pc instance1 (
    .clk(clk),
    .d_in(new_pc),
    .d_out(addr),
    .en_pc(done),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bigger.v:43" *)
  memory instance2 (
    .addr(addr),
    .clk(clk),
    .out(mem_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bigger.v:88" *)
  bitty instance3 (
    .clk(clk),
    .d_instr(mem_out),
    .d_out(d_out),
    .done(done),
    .reset(reset),
    .run(run_bitty)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bigger.v:27" *)
  branch_logic instance4 (
    .address(addr),
    .done(done),
    .instruction(mem_out),
    .last_alu_result(d_out),
    .new_pc(new_pc)
  );
  assign _05_[0] = cur_state[0];
  assign _06_[1] = cur_state[1];
  assign _02_[0] = _01_[0];
  assign instr = mem_out;
endmodule
