/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "cpu.v:8" *)
module cpu(clk, run, reset, d_inst, mux_sel, done, sel, en_s, en_c, en, en_inst, im_d);
  (* src = "cpu.v:37" *)
  wire [7:0] _000_;
  (* src = "cpu.v:37" *)
  wire _001_;
  (* src = "cpu.v:37" *)
  wire [3:0] _002_;
  (* src = "cpu.v:37" *)
  wire [2:0] _003_;
  (* src = "cpu.v:37" *)
  wire [7:0] _004_;
  (* src = "cpu.v:37" *)
  wire [3:0] _005_;
  (* src = "cpu.v:37" *)
  wire [3:0] _006_;
  (* src = "cpu.v:37" *)
  wire [3:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire [2:0] _016_;
  wire [1:0] _017_;
  wire [2:0] _018_;
  wire [1:0] _019_;
  wire [2:0] _020_;
  wire [1:0] _021_;
  wire [2:0] _022_;
  wire [1:0] _023_;
  wire [2:0] _024_;
  wire [1:0] _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire [1:0] _030_;
  wire [2:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire [1:0] _037_;
  wire [1:0] _038_;
  wire [2:0] _039_;
  wire [1:0] _040_;
  wire [1:0] _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  (* src = "cpu.v:157|cpu.v:154|<techmap.v>:432" *)
  wire [5:0] _059_;
  wire _060_;
  (* src = "cpu.v:82|cpu.v:61|<techmap.v>:432" *)
  wire [7:0] _061_;
  (* src = "cpu.v:82|cpu.v:61|<techmap.v>:428" *)
  wire [3:0] _062_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _063_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _064_;
  (* src = "cpu.v:157|cpu.v:154|<techmap.v>:445" *)
  wire _065_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _066_;
  (* src = "cpu.v:82|cpu.v:61|<techmap.v>:445" *)
  wire _067_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _068_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _069_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _070_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _071_;
  (* src = "cpu.v:111|<techmap.v>:445" *)
  wire _072_;
  (* src = "cpu.v:9" *)
  input clk;
  (* src = "cpu.v:29" *)
  reg [1:0] cur_state;
  (* src = "cpu.v:12" *)
  input [15:0] d_inst;
  (* src = "cpu.v:15" *)
  output done;
  (* src = "cpu.v:20" *)
  output [7:0] en;
  (* src = "cpu.v:19" *)
  output en_c;
  (* src = "cpu.v:21" *)
  output en_inst;
  (* src = "cpu.v:18" *)
  output en_s;
  (* src = "cpu.v:30" *)
  wire [1:0] format;
  (* src = "cpu.v:22" *)
  output [15:0] im_d;
  (* src = "cpu.v:14" *)
  output [3:0] mux_sel;
  (* src = "cpu.v:29" *)
  wire [1:0] next_state;
  (* src = "cpu.v:11" *)
  input reset;
  (* src = "cpu.v:10" *)
  input run;
  (* src = "cpu.v:17" *)
  output [2:0] sel;
  assign _007_[0] = _037_[0] |(* src = "cpu.v:88" *)  d_inst[1];
  assign _001_ = d_inst[0] |(* src = "cpu.v:110" *)  _038_[1];
  assign _008_ = _017_[0] | _017_[1];
  assign _018_[0] = _057_ | _056_;
  assign _019_[0] = _018_[0] | _018_[1];
  assign _012_ = _019_[0] | _017_[1];
  assign _020_[1] = _056_ | _054_;
  assign _021_[0] = _016_[0] | _020_[1];
  assign _014_ = _021_[0] | _017_[1];
  assign _022_[0] = _058_ | _056_;
  assign _023_[0] = _022_[0] | _018_[1];
  assign _015_ = _023_[0] | _017_[1];
  assign _025_[1] = _024_[2] | _053_;
  assign _013_ = _017_[0] | _025_[1];
  assign _042_ = _026_ |(* src = "cpu.v:111" *)  _039_[2];
  assign _027_ = d_inst[13] |(* src = "cpu.v:111" *)  _039_[1];
  assign _043_ = _027_ |(* src = "cpu.v:111" *)  _039_[2];
  assign _028_ = _039_[0] |(* src = "cpu.v:111" *)  d_inst[14];
  assign _044_ = _028_ |(* src = "cpu.v:111" *)  _039_[2];
  assign _045_ = _029_ |(* src = "cpu.v:111" *)  _039_[2];
  assign _026_ = _039_[0] |(* src = "cpu.v:111" *)  _039_[1];
  assign _046_ = _026_ |(* src = "cpu.v:111" *)  d_inst[15];
  assign _047_ = _027_ |(* src = "cpu.v:111" *)  d_inst[15];
  assign _048_ = _028_ |(* src = "cpu.v:111" *)  d_inst[15];
  assign _016_[0] = _058_ | _057_;
  assign _016_[1] = _056_ | _055_;
  assign _024_[2] = _054_ | _052_;
  assign _017_[0] = _016_[0] | _016_[1];
  assign _030_[1] = _024_[2] | _051_;
  assign _009_ = _017_[0] | _030_[1];
  assign _031_[2] = _054_ | _051_;
  assign _032_[1] = _031_[2] | _053_;
  assign _010_ = _017_[0] | _032_[1];
  assign _018_[1] = _055_ | _054_;
  assign _016_[2] = _052_ | _051_;
  assign _033_[0] = _016_[0] | _018_[1];
  assign _017_[1] = _016_[2] | _053_;
  assign _011_ = _033_[0] | _017_[1];
  assign en_inst = _060_ | done;
  assign _049_ = _040_[0] |(* src = "cpu.v:82|cpu.v:61" *)  cur_state[1];
  assign _050_ = cur_state[0] |(* src = "cpu.v:108|cpu.v:61" *)  _041_[1];
  assign _034_ = done |(* src = "cpu.v:157|cpu.v:154|<techmap.v>:445" *)  en_c;
  assign _065_ = _034_ |(* src = "cpu.v:157|cpu.v:154|<techmap.v>:445" *)  _060_;
  assign _066_ = _013_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _051_;
  assign _068_ = _010_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _052_;
  assign _069_ = _008_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _054_;
  assign _070_ = _011_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _056_;
  assign _071_ = _058_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _012_;
  assign _072_ = _014_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _055_;
  assign _063_ = _009_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _053_;
  assign _064_ = _015_ |(* src = "cpu.v:111|<techmap.v>:445" *)  _057_;
  assign _062_[3] = _061_[3] |(* src = "cpu.v:82|cpu.v:61|<techmap.v>:441" *)  _061_[7];
  assign _062_[2] = _061_[2] |(* src = "cpu.v:82|cpu.v:61|<techmap.v>:441" *)  _061_[6];
  assign _062_[1] = _061_[1] |(* src = "cpu.v:82|cpu.v:61|<techmap.v>:441" *)  _061_[5];
  assign _062_[0] = _061_[0] |(* src = "cpu.v:82|cpu.v:61|<techmap.v>:441" *)  _061_[4];
  assign _067_ = en_c |(* src = "cpu.v:82|cpu.v:61|<techmap.v>:445" *)  _060_;
  assign _006_[3] = d_inst[0] |(* src = "cpu.v:84" *)  d_inst[1];
  assign _029_ = d_inst[13] |(* src = "cpu.v:111" *)  d_inst[14];
  assign _035_ = _029_ |(* src = "cpu.v:111" *)  d_inst[15];
  assign _036_ = cur_state[0] |(* src = "cpu.v:62|cpu.v:61" *)  cur_state[1];
  assign _058_ = ~(* src = "cpu.v:111" *) _042_;
  assign _051_ = ~(* src = "cpu.v:111" *) _043_;
  assign _052_ = ~(* src = "cpu.v:111" *) _044_;
  assign _053_ = ~(* src = "cpu.v:111" *) _045_;
  assign _054_ = ~(* src = "cpu.v:111" *) _046_;
  assign _055_ = ~(* src = "cpu.v:111" *) _047_;
  assign _056_ = ~(* src = "cpu.v:111" *) _048_;
  assign _057_ = ~(* src = "cpu.v:111" *) _035_;
  assign en_c = ~(* src = "cpu.v:82|cpu.v:61" *) _049_;
  assign _060_ = ~(* src = "cpu.v:62|cpu.v:61" *) _036_;
  assign _000_[0] = _001_ ? (* src = "cpu.v:110" *) _004_[0] : 1'h0;
  assign _000_[1] = _001_ ? (* src = "cpu.v:110" *) _004_[1] : 1'h0;
  assign _000_[2] = _001_ ? (* src = "cpu.v:110" *) _004_[2] : 1'h0;
  assign _000_[3] = _001_ ? (* src = "cpu.v:110" *) _004_[3] : 1'h0;
  assign _000_[4] = _001_ ? (* src = "cpu.v:110" *) _004_[4] : 1'h0;
  assign _000_[5] = _001_ ? (* src = "cpu.v:110" *) _004_[5] : 1'h0;
  assign _000_[6] = _001_ ? (* src = "cpu.v:110" *) _004_[6] : 1'h0;
  assign _000_[7] = _001_ ? (* src = "cpu.v:110" *) _004_[7] : 1'h0;
  assign _006_[0] = _006_[3] ? (* src = "cpu.v:84" *) _007_[0] : d_inst[10];
  assign _006_[1] = _006_[3] ? (* src = "cpu.v:84" *) 1'h0 : d_inst[11];
  assign _006_[2] = _006_[3] ? (* src = "cpu.v:84" *) 1'h0 : d_inst[12];
  assign _003_[0] = _001_ ? (* src = "cpu.v:83" *) d_inst[2] : 1'h0;
  assign _003_[1] = _001_ ? (* src = "cpu.v:83" *) d_inst[3] : 1'h0;
  assign _003_[2] = _001_ ? (* src = "cpu.v:83" *) d_inst[4] : 1'h0;
  assign _005_[0] = _001_ ? (* src = "cpu.v:83" *) _006_[0] : 1'h1;
  assign _005_[1] = _001_ ? (* src = "cpu.v:83" *) _006_[1] : 1'h0;
  assign _005_[2] = _001_ ? (* src = "cpu.v:83" *) _006_[2] : 1'h0;
  assign _005_[3] = _001_ ? (* src = "cpu.v:83" *) _006_[3] : 1'h1;
  assign _002_[0] = _001_ ? (* src = "cpu.v:63" *) d_inst[13] : 1'h1;
  assign _002_[1] = _001_ ? (* src = "cpu.v:63" *) d_inst[14] : 1'h0;
  assign _002_[2] = _001_ ? (* src = "cpu.v:63" *) d_inst[15] : 1'h0;
  assign _002_[3] = ~(* src = "cpu.v:63" *) _001_;
  assign done = ~(* src = "cpu.v:108|cpu.v:61" *) _050_;
  assign sel[0] = _049_ ? (* src = "cpu.v:82|cpu.v:61" *) 1'h0 : _003_[0];
  assign sel[1] = _049_ ? (* src = "cpu.v:82|cpu.v:61" *) 1'h0 : _003_[1];
  assign sel[2] = _049_ ? (* src = "cpu.v:82|cpu.v:61" *) 1'h0 : _003_[2];
  assign en_s = _036_ ? (* src = "cpu.v:62|cpu.v:61" *) 1'h0 : _001_;
  assign en[0] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[0];
  assign en[1] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[1];
  assign en[2] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[2];
  assign en[3] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[3];
  assign en[4] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[4];
  assign en[5] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[5];
  assign en[6] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[6];
  assign en[7] = _050_ ? (* src = "cpu.v:108|cpu.v:61" *) 1'h0 : _000_[7];
  assign next_state[0] = _065_ ? (* src = "cpu.v:157|cpu.v:154|<techmap.v>:445" *) _059_[4] : 1'h0;
  assign next_state[1] = _065_ ? (* src = "cpu.v:157|cpu.v:154|<techmap.v>:445" *) en_c : 1'h0;
  assign _004_[6] = _066_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _051_ : 1'hx;
  assign _004_[5] = _068_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _052_ : 1'hx;
  assign _004_[3] = _069_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _054_ : 1'hx;
  assign _004_[1] = _070_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _056_ : 1'hx;
  assign _004_[7] = _071_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _058_ : 1'hx;
  assign _004_[2] = _072_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _055_ : 1'hx;
  assign _004_[4] = _063_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _053_ : 1'hx;
  assign _004_[0] = _064_ ? (* src = "cpu.v:111|<techmap.v>:445" *) _057_ : 1'hx;
  assign mux_sel[0] = _067_ ? (* src = "cpu.v:82|cpu.v:61|<techmap.v>:445" *) _062_[0] : 1'h1;
  assign mux_sel[1] = _067_ ? (* src = "cpu.v:82|cpu.v:61|<techmap.v>:445" *) _062_[1] : 1'h0;
  assign mux_sel[2] = _067_ ? (* src = "cpu.v:82|cpu.v:61|<techmap.v>:445" *) _062_[2] : 1'h0;
  assign mux_sel[3] = _067_ ? (* src = "cpu.v:82|cpu.v:61|<techmap.v>:445" *) _062_[3] : 1'h1;
  (* src = "cpu.v:137" *)
  always @(posedge clk or posedge reset)
    if (reset)
      cur_state[0] <= 0;
    else
      cur_state[0] <= next_state[0];
  (* src = "cpu.v:137" *)
  always @(posedge clk or posedge reset)
    if (reset)
      cur_state[1] <= 0;
    else
      cur_state[1] <= next_state[1];
  assign _037_[0] = d_inst[0] ^(* src = "cpu.v:88" *)  1'h1;
  assign _038_[1] = d_inst[1] ^(* src = "cpu.v:110" *)  1'h1;
  assign _039_[2] = d_inst[15] ^(* src = "cpu.v:111" *)  1'h1;
  assign _039_[1] = d_inst[14] ^(* src = "cpu.v:111" *)  1'h1;
  assign _039_[0] = d_inst[13] ^(* src = "cpu.v:111" *)  1'h1;
  assign _040_[0] = cur_state[0] ^(* src = "cpu.v:82|cpu.v:61" *)  1'h1;
  assign _041_[1] = cur_state[1] ^(* src = "cpu.v:108|cpu.v:61" *)  1'h1;
  assign _059_[4] = run &(* src = "cpu.v:157|cpu.v:154|<techmap.v>:434" *)  _060_;
  assign _061_[4] = _002_[0] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  _060_;
  assign _061_[5] = _002_[1] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  _060_;
  assign _061_[6] = _002_[2] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  _060_;
  assign _061_[7] = _002_[3] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  _060_;
  assign _061_[0] = _005_[0] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  en_c;
  assign _061_[1] = _005_[1] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  en_c;
  assign _061_[2] = _005_[2] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  en_c;
  assign _061_[3] = _005_[3] &(* src = "cpu.v:82|cpu.v:61|<techmap.v>:434" *)  en_c;
  assign _007_[3:1] = 3'h4;
  assign _018_[2] = _016_[2];
  assign _019_[1] = _017_[1];
  assign { _020_[2], _020_[0] } = { _016_[2], _016_[0] };
  assign _021_[1] = _017_[1];
  assign _022_[2:1] = { _016_[2], _018_[1] };
  assign _023_[1] = _017_[1];
  assign _024_[1:0] = _016_[1:0];
  assign _025_[0] = _017_[0];
  assign _030_[0] = _017_[0];
  assign _031_[1:0] = _016_[1:0];
  assign _032_[0] = _017_[0];
  assign _033_[1] = _017_[1];
  assign _037_[1] = d_inst[1];
  assign _038_[0] = d_inst[0];
  assign _040_[1] = cur_state[1];
  assign _041_[0] = cur_state[0];
  assign { _059_[5], _059_[3:0] } = { 1'h0, en_c, 3'h0 };
  assign format = d_inst[1:0];
  assign im_d = { 8'h00, d_inst[12:5] };
endmodule
