/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "cpu.v:3" *)
module cpu(clk, run, reset, d_inst, mux_sel, done, sel, en_s, en_c, en, en_inst, im_d);
  (* src = "cpu.v:32" *)
  wire [15:0] _000_;
  (* src = "cpu.v:32" *)
  wire [3:0] _001_;
  (* src = "cpu.v:32" *)
  wire _002_;
  (* src = "cpu.v:32" *)
  wire [7:0] _003_;
  (* src = "cpu.v:32" *)
  wire _004_;
  (* src = "cpu.v:32" *)
  wire _005_;
  (* src = "cpu.v:32" *)
  wire _006_;
  (* src = "cpu.v:32" *)
  wire [2:0] _007_;
  (* src = "cpu.v:32" *)
  wire [7:0] _008_;
  (* src = "cpu.v:32" *)
  wire _009_;
  (* src = "cpu.v:32" *)
  wire [3:0] _010_;
  (* src = "cpu.v:32" *)
  wire [2:0] _011_;
  (* src = "cpu.v:32" *)
  wire [7:0] _012_;
  (* src = "cpu.v:32" *)
  wire [15:0] _013_;
  (* src = "cpu.v:32" *)
  wire [3:0] _014_;
  (* src = "cpu.v:32" *)
  wire [3:0] _015_;
  (* src = "cpu.v:32" *)
  wire [3:0] _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire [2:0] _031_;
  wire [1:0] _032_;
  wire [2:0] _033_;
  wire [1:0] _034_;
  wire [1:0] _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire [2:0] _040_;
  wire [1:0] _041_;
  wire [2:0] _042_;
  wire [1:0] _043_;
  wire [1:0] _044_;
  wire [2:0] _045_;
  wire [1:0] _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire [1:0] _051_;
  wire [1:0] _052_;
  wire [2:0] _053_;
  wire [1:0] _054_;
  wire [1:0] _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "cpu.v:127|cpu.v:124|<techmap.v>:432" *)
  wire [5:0] _072_;
  (* src = "cpu.v:127|cpu.v:124|<techmap.v>:428" *)
  wire [1:0] _073_;
  wire _074_;
  (* src = "cpu.v:69|cpu.v:49|<techmap.v>:432" *)
  wire [7:0] _075_;
  (* src = "cpu.v:69|cpu.v:49|<techmap.v>:428" *)
  wire [3:0] _076_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _077_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _078_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _079_;
  (* src = "cpu.v:127|cpu.v:124|<techmap.v>:445" *)
  wire _080_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _081_;
  (* src = "cpu.v:69|cpu.v:49|<techmap.v>:445" *)
  wire _082_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _083_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _084_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _085_;
  (* src = "cpu.v:92|<techmap.v>:445" *)
  wire _086_;
  (* src = "cpu.v:126" *)
  wire [1:0] _087_;
  (* src = "cpu.v:127" *)
  wire [1:0] _088_;
  (* src = "cpu.v:4" *)
  input clk;
  (* src = "cpu.v:27" *)
  reg [1:0] cur_state;
  (* src = "cpu.v:7" *)
  input [15:0] d_inst;
  (* src = "cpu.v:10" *)
  output done;
  (* src = "cpu.v:15" *)
  output [7:0] en;
  (* src = "cpu.v:14" *)
  output en_c;
  (* src = "cpu.v:16" *)
  output en_inst;
  (* src = "cpu.v:13" *)
  output en_s;
  (* src = "cpu.v:28" *)
  wire [1:0] format;
  (* src = "cpu.v:17" *)
  output [15:0] im_d;
  (* src = "cpu.v:9" *)
  output [3:0] mux_sel;
  (* src = "cpu.v:27" *)
  wire [1:0] next_state;
  (* src = "cpu.v:6" *)
  input reset;
  (* src = "cpu.v:5" *)
  input run;
  (* src = "cpu.v:12" *)
  output [2:0] sel;
  assign _016_[0] = _051_[0] |(* src = "cpu.v:74" *)  d_inst[1];
  assign _009_ = d_inst[0] |(* src = "cpu.v:91" *)  _052_[1];
  assign _031_[0] = _071_ | _069_;
  assign _032_[0] = _031_[0] | _031_[1];
  assign _022_ = _032_[0] | _032_[1];
  assign _034_[1] = _033_[2] | _065_;
  assign _023_ = _034_[0] | _034_[1];
  assign _024_ = _034_[0] | _032_[1];
  assign _035_[0] = _033_[0] | _031_[1];
  assign _018_ = _035_[0] | _032_[1];
  assign _056_ = _036_ |(* src = "cpu.v:92" *)  _053_[2];
  assign _057_ = _037_ |(* src = "cpu.v:92" *)  _053_[2];
  assign _058_ = _038_ |(* src = "cpu.v:92" *)  _053_[2];
  assign _059_ = _039_ |(* src = "cpu.v:92" *)  _053_[2];
  assign _036_ = _053_[0] |(* src = "cpu.v:92" *)  _053_[1];
  assign _060_ = _036_ |(* src = "cpu.v:92" *)  d_inst[15];
  assign _037_ = d_inst[13] |(* src = "cpu.v:92" *)  _053_[1];
  assign _061_ = _037_ |(* src = "cpu.v:92" *)  d_inst[15];
  assign _038_ = _053_[0] |(* src = "cpu.v:92" *)  d_inst[14];
  assign _062_ = _038_ |(* src = "cpu.v:92" *)  d_inst[15];
  assign _033_[0] = _071_ | _070_;
  assign _040_[1] = _069_ | _067_;
  assign _031_[2] = _066_ | _065_;
  assign _041_[0] = _033_[0] | _040_[1];
  assign _032_[1] = _031_[2] | _064_;
  assign _019_ = _041_[0] | _032_[1];
  assign _005_ = _054_[0] |(* src = "cpu.v:69|cpu.v:49" *)  cur_state[1];
  assign _063_ = cur_state[0] |(* src = "cpu.v:90|cpu.v:49" *)  _055_[1];
  assign _042_[0] = _070_ | _069_;
  assign _031_[1] = _068_ | _067_;
  assign _043_[0] = _042_[0] | _031_[1];
  assign _020_ = _043_[0] | _032_[1];
  assign _033_[1] = _069_ | _068_;
  assign _033_[2] = _067_ | _066_;
  assign _034_[0] = _033_[0] | _033_[1];
  assign _044_[1] = _033_[2] | _064_;
  assign _017_ = _034_[0] | _044_[1];
  assign _045_[2] = _067_ | _065_;
  assign _046_[1] = _045_[2] | _064_;
  assign _021_ = _034_[0] | _046_[1];
  assign _029_ = _030_ |(* src = "cpu.v:32" *)  reset;
  assign _083_ = _020_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _071_;
  assign _084_ = _017_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _065_;
  assign _081_ = _022_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _070_;
  assign _085_ = _024_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _067_;
  assign _073_[0] = _047_ |(* src = "cpu.v:127|cpu.v:124|<techmap.v>:441" *)  _072_[4];
  assign _086_ = _069_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _018_;
  assign _048_ = _072_[1] |(* src = "cpu.v:127|cpu.v:124|<techmap.v>:441" *)  _072_[3];
  assign _077_ = _021_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _066_;
  assign _049_ = _002_ |(* src = "cpu.v:127|cpu.v:124|<techmap.v>:445" *)  _004_;
  assign _080_ = _049_ |(* src = "cpu.v:127|cpu.v:124|<techmap.v>:445" *)  _074_;
  assign _079_ = _019_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _068_;
  assign _078_ = _023_ |(* src = "cpu.v:92|<techmap.v>:445" *)  _064_;
  assign _076_[3] = _075_[3] |(* src = "cpu.v:69|cpu.v:49|<techmap.v>:441" *)  _075_[7];
  assign _076_[2] = _075_[2] |(* src = "cpu.v:69|cpu.v:49|<techmap.v>:441" *)  _075_[6];
  assign _076_[1] = _075_[1] |(* src = "cpu.v:69|cpu.v:49|<techmap.v>:441" *)  _075_[5];
  assign _076_[0] = _075_[0] |(* src = "cpu.v:69|cpu.v:49|<techmap.v>:441" *)  _075_[4];
  assign _082_ = _004_ |(* src = "cpu.v:69|cpu.v:49|<techmap.v>:445" *)  _074_;
  assign _015_[3] = d_inst[0] |(* src = "cpu.v:71" *)  d_inst[1];
  assign _039_ = d_inst[13] |(* src = "cpu.v:92" *)  d_inst[14];
  assign _050_ = _039_ |(* src = "cpu.v:92" *)  d_inst[15];
  assign _026_ = cur_state[0] |(* src = "cpu.v:50|cpu.v:49" *)  cur_state[1];
  assign _069_ = ~(* src = "cpu.v:92" *) _056_;
  assign _070_ = ~(* src = "cpu.v:92" *) _057_;
  assign _071_ = ~(* src = "cpu.v:92" *) _058_;
  assign _064_ = ~(* src = "cpu.v:92" *) _059_;
  assign _065_ = ~(* src = "cpu.v:92" *) _060_;
  assign _066_ = ~(* src = "cpu.v:92" *) _061_;
  assign _067_ = ~(* src = "cpu.v:92" *) _062_;
  assign _068_ = ~(* src = "cpu.v:92" *) _050_;
  assign _004_ = ~(* src = "cpu.v:69|cpu.v:49" *) _005_;
  assign _074_ = ~(* src = "cpu.v:50|cpu.v:49" *) _026_;
  assign _087_[0] = ~(* src = "cpu.v:126" *) en_c;
  assign _088_[1] = ~(* src = "cpu.v:127" *) done;
  assign _008_[0] = _009_ ? (* src = "cpu.v:91" *) _012_[0] : 1'h0;
  assign _008_[1] = _009_ ? (* src = "cpu.v:91" *) _012_[1] : 1'h0;
  assign _008_[2] = _009_ ? (* src = "cpu.v:91" *) _012_[2] : 1'h0;
  assign _008_[3] = _009_ ? (* src = "cpu.v:91" *) _012_[3] : 1'h0;
  assign _008_[4] = _009_ ? (* src = "cpu.v:91" *) _012_[4] : 1'h0;
  assign _008_[5] = _009_ ? (* src = "cpu.v:91" *) _012_[5] : 1'h0;
  assign _008_[6] = _009_ ? (* src = "cpu.v:91" *) _012_[6] : 1'h0;
  assign _008_[7] = _009_ ? (* src = "cpu.v:91" *) _012_[7] : 1'h0;
  assign _015_[0] = _015_[3] ? (* src = "cpu.v:71" *) _016_[0] : d_inst[10];
  assign _015_[1] = _015_[3] ? (* src = "cpu.v:71" *) 1'h0 : d_inst[11];
  assign _015_[2] = _015_[3] ? (* src = "cpu.v:71" *) 1'h0 : d_inst[12];
  assign _011_[0] = _009_ ? (* src = "cpu.v:70" *) d_inst[2] : 1'h0;
  assign _011_[1] = _009_ ? (* src = "cpu.v:70" *) d_inst[3] : 1'h0;
  assign _011_[2] = _009_ ? (* src = "cpu.v:70" *) d_inst[4] : 1'h0;
  assign _014_[0] = _009_ ? (* src = "cpu.v:70" *) _015_[0] : 1'h1;
  assign _014_[1] = _009_ ? (* src = "cpu.v:70" *) _015_[1] : 1'h0;
  assign _014_[2] = _009_ ? (* src = "cpu.v:70" *) _015_[2] : 1'h0;
  assign _014_[3] = _009_ ? (* src = "cpu.v:70" *) _015_[3] : 1'h0;
  assign _013_[0] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[5];
  assign _013_[1] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[6];
  assign _013_[2] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[7];
  assign _013_[3] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[8];
  assign _013_[4] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[9];
  assign _013_[5] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[10];
  assign _013_[6] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[11];
  assign _013_[7] = _016_[0] ? (* src = "cpu.v:54" *) 1'h0 : d_inst[12];
  assign _000_[0] = _009_ ? (* src = "cpu.v:51" *) _013_[0] : 1'h0;
  assign _000_[1] = _009_ ? (* src = "cpu.v:51" *) _013_[1] : 1'h0;
  assign _000_[2] = _009_ ? (* src = "cpu.v:51" *) _013_[2] : 1'h0;
  assign _000_[3] = _009_ ? (* src = "cpu.v:51" *) _013_[3] : 1'h0;
  assign _000_[4] = _009_ ? (* src = "cpu.v:51" *) _013_[4] : 1'h0;
  assign _000_[5] = _009_ ? (* src = "cpu.v:51" *) _013_[5] : 1'h0;
  assign _000_[6] = _009_ ? (* src = "cpu.v:51" *) _013_[6] : 1'h0;
  assign _000_[7] = _009_ ? (* src = "cpu.v:51" *) _013_[7] : 1'h0;
  assign _010_[0] = _009_ ? (* src = "cpu.v:51" *) d_inst[13] : 1'h1;
  assign _010_[1] = _009_ ? (* src = "cpu.v:51" *) d_inst[14] : 1'h0;
  assign _010_[2] = _009_ ? (* src = "cpu.v:51" *) d_inst[15] : 1'h0;
  assign _010_[3] = ~(* src = "cpu.v:51" *) _009_;
  assign _002_ = ~(* src = "cpu.v:90|cpu.v:49" *) _063_;
  assign _006_ = _026_ ? (* src = "cpu.v:50|cpu.v:49" *) 1'h0 : _009_;
  assign _003_[0] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[0];
  assign _003_[1] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[1];
  assign _003_[2] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[2];
  assign _003_[3] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[3];
  assign _003_[4] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[4];
  assign _003_[5] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[5];
  assign _003_[6] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[6];
  assign _003_[7] = _063_ ? (* src = "cpu.v:90|cpu.v:49" *) 1'h0 : _008_[7];
  assign _007_[0] = _005_ ? (* src = "cpu.v:69|cpu.v:49" *) 1'h0 : _011_[0];
  assign _007_[1] = _005_ ? (* src = "cpu.v:69|cpu.v:49" *) 1'h0 : _011_[1];
  assign _007_[2] = _005_ ? (* src = "cpu.v:69|cpu.v:49" *) 1'h0 : _011_[2];
  assign sel[0] = reset ? (* src = "cpu.v:33" *) 1'h0 : _007_[0];
  assign sel[1] = reset ? (* src = "cpu.v:33" *) 1'h0 : _007_[1];
  assign sel[2] = reset ? (* src = "cpu.v:33" *) 1'h0 : _007_[2];
  assign en_inst = reset ? (* src = "cpu.v:33" *) 1'h0 : _005_;
  assign en[0] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[0];
  assign en[1] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[1];
  assign en[2] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[2];
  assign en[3] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[3];
  assign en[4] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[4];
  assign en[5] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[5];
  assign en[6] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[6];
  assign en[7] = reset ? (* src = "cpu.v:33" *) 1'h0 : _003_[7];
  assign en_s = reset ? (* src = "cpu.v:33" *) 1'h0 : _006_;
  assign done = reset ? (* src = "cpu.v:33" *) 1'h0 : _002_;
  assign en_c = reset ? (* src = "cpu.v:33" *) 1'h0 : _004_;
  assign _012_[5] = _083_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _071_ : 1'hx;
  assign _012_[6] = _081_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _070_ : 1'hx;
  assign _012_[1] = _085_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _067_ : 1'hx;
  assign next_state[0] = _080_ ? (* src = "cpu.v:127|cpu.v:124|<techmap.v>:445" *) _073_[0] : 1'h0;
  assign next_state[1] = _080_ ? (* src = "cpu.v:127|cpu.v:124|<techmap.v>:445" *) _048_ : 1'h0;
  assign _012_[7] = _086_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _069_ : 1'hx;
  assign _012_[2] = _077_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _066_ : 1'hx;
  assign _012_[3] = _084_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _065_ : 1'hx;
  assign _012_[4] = _078_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _064_ : 1'hx;
  assign _012_[0] = _079_ ? (* src = "cpu.v:92|<techmap.v>:445" *) _068_ : 1'hx;
  assign _001_[0] = _082_ ? (* src = "cpu.v:69|cpu.v:49|<techmap.v>:445" *) _076_[0] : 1'h1;
  assign _001_[1] = _082_ ? (* src = "cpu.v:69|cpu.v:49|<techmap.v>:445" *) _076_[1] : 1'h0;
  assign _001_[2] = _082_ ? (* src = "cpu.v:69|cpu.v:49|<techmap.v>:445" *) _076_[2] : 1'h0;
  assign _001_[3] = _082_ ? (* src = "cpu.v:69|cpu.v:49|<techmap.v>:445" *) _076_[3] : 1'h1;
  assign _025_ = ~reset;
  assign _027_ = ~_029_;
  (* src = "cpu.v:111" *)
  always @(posedge clk or posedge reset)
    if (reset)
      cur_state[0] <= 0;
    else
      cur_state[0] <= next_state[0];
  (* src = "cpu.v:111" *)
  always @(posedge clk or posedge reset)
    if (reset)
      cur_state[1] <= 0;
    else
      cur_state[1] <= next_state[1];
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _247_ (
    .D(_001_[0]),
    .E(_025_),
    .Q(mux_sel[0])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _248_ (
    .D(_001_[1]),
    .E(_025_),
    .Q(mux_sel[1])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _249_ (
    .D(_001_[2]),
    .E(_025_),
    .Q(mux_sel[2])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _250_ (
    .D(_001_[3]),
    .E(_025_),
    .Q(mux_sel[3])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _251_ (
    .D(_000_[0]),
    .E(_027_),
    .Q(im_d[0])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _252_ (
    .D(_000_[1]),
    .E(_027_),
    .Q(im_d[1])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _253_ (
    .D(_000_[2]),
    .E(_027_),
    .Q(im_d[2])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _254_ (
    .D(_000_[3]),
    .E(_027_),
    .Q(im_d[3])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _255_ (
    .D(_000_[4]),
    .E(_027_),
    .Q(im_d[4])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _256_ (
    .D(_000_[5]),
    .E(_027_),
    .Q(im_d[5])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _257_ (
    .D(_000_[6]),
    .E(_027_),
    .Q(im_d[6])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _258_ (
    .D(_000_[7]),
    .E(_027_),
    .Q(im_d[7])
  );
  (* src = "cpu.v:32" *)
  \$_DLATCH_P_  _259_ (
    .D(1'h0),
    .E(_027_),
    .Q(im_d[12])
  );
  assign _051_[0] = d_inst[0] ^(* src = "cpu.v:74" *)  1'h1;
  assign _052_[1] = d_inst[1] ^(* src = "cpu.v:91" *)  1'h1;
  assign _053_[2] = d_inst[15] ^(* src = "cpu.v:92" *)  1'h1;
  assign _053_[1] = d_inst[14] ^(* src = "cpu.v:92" *)  1'h1;
  assign _053_[0] = d_inst[13] ^(* src = "cpu.v:92" *)  1'h1;
  assign _054_[0] = cur_state[0] ^(* src = "cpu.v:69|cpu.v:49" *)  1'h1;
  assign _055_[1] = cur_state[1] ^(* src = "cpu.v:90|cpu.v:49" *)  1'h1;
  assign _028_ = _025_ &(* src = "cpu.v:32" *)  _026_;
  assign _030_ = _025_ &(* src = "cpu.v:32" *)  _028_;
  assign _072_[1] = _088_[1] &(* src = "cpu.v:127|cpu.v:124|<techmap.v>:434" *)  _002_;
  assign _047_ = _087_[0] &(* src = "cpu.v:127|cpu.v:124|<techmap.v>:434" *)  _004_;
  assign _072_[3] = en_c &(* src = "cpu.v:127|cpu.v:124|<techmap.v>:434" *)  _004_;
  assign _072_[4] = run &(* src = "cpu.v:127|cpu.v:124|<techmap.v>:434" *)  _074_;
  assign _075_[4] = _010_[0] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _074_;
  assign _075_[5] = _010_[1] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _074_;
  assign _075_[6] = _010_[2] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _074_;
  assign _075_[7] = _010_[3] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _074_;
  assign _075_[0] = _014_[0] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _004_;
  assign _075_[1] = _014_[1] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _004_;
  assign _075_[2] = _014_[2] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _004_;
  assign _075_[3] = _014_[3] &(* src = "cpu.v:69|cpu.v:49|<techmap.v>:434" *)  _004_;
  assign _000_[15:8] = 8'h00;
  assign _013_[15:8] = 8'h00;
  assign _016_[3:1] = 3'h4;
  assign _035_[1] = _032_[1];
  assign { _040_[2], _040_[0] } = { _031_[2], _033_[0] };
  assign _041_[1] = _032_[1];
  assign _042_[2:1] = _031_[2:1];
  assign _043_[1] = _032_[1];
  assign _044_[0] = _034_[0];
  assign _045_[1:0] = _033_[1:0];
  assign _046_[0] = _034_[0];
  assign _051_[1] = d_inst[1];
  assign _052_[0] = d_inst[0];
  assign _054_[1] = cur_state[1];
  assign _055_[0] = cur_state[0];
  assign { _072_[5], _072_[2], _072_[0] } = { 1'h0, _047_, 1'h0 };
  assign _073_[1] = _048_;
  assign _087_[1] = en_c;
  assign _088_[0] = 1'h0;
  assign format = d_inst[1:0];
  assign { im_d[15:13], im_d[11:8] } = { im_d[12], im_d[12], im_d[12], im_d[12], im_d[12], im_d[12], im_d[12] };
endmodule
