/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "dff.v:3" *)
module dff(clk, en, d_in, starting, reset, mux_out);
  (* src = "dff.v:13" *)
  wire [15:0] _00_;
  (* src = "dff.v:13" *)
  wire [15:0] _01_;
  (* src = "dff.v:4" *)
  input clk;
  (* src = "dff.v:6" *)
  input [15:0] d_in;
  (* src = "dff.v:5" *)
  input en;
  (* src = "dff.v:10" *)
  output [15:0] mux_out;
  reg [15:0] mux_out;
  (* src = "dff.v:8" *)
  input reset;
  (* src = "dff.v:7" *)
  input [15:0] starting;
  assign _01_[0] = en ? (* src = "dff.v:18" *) d_in[0] : mux_out[0];
  assign _01_[1] = en ? (* src = "dff.v:18" *) d_in[1] : mux_out[1];
  assign _01_[2] = en ? (* src = "dff.v:18" *) d_in[2] : mux_out[2];
  assign _01_[3] = en ? (* src = "dff.v:18" *) d_in[3] : mux_out[3];
  assign _01_[4] = en ? (* src = "dff.v:18" *) d_in[4] : mux_out[4];
  assign _01_[5] = en ? (* src = "dff.v:18" *) d_in[5] : mux_out[5];
  assign _01_[6] = en ? (* src = "dff.v:18" *) d_in[6] : mux_out[6];
  assign _01_[7] = en ? (* src = "dff.v:18" *) d_in[7] : mux_out[7];
  assign _01_[8] = en ? (* src = "dff.v:18" *) d_in[8] : mux_out[8];
  assign _01_[9] = en ? (* src = "dff.v:18" *) d_in[9] : mux_out[9];
  assign _01_[10] = en ? (* src = "dff.v:18" *) d_in[10] : mux_out[10];
  assign _01_[11] = en ? (* src = "dff.v:18" *) d_in[11] : mux_out[11];
  assign _01_[12] = en ? (* src = "dff.v:18" *) d_in[12] : mux_out[12];
  assign _01_[13] = en ? (* src = "dff.v:18" *) d_in[13] : mux_out[13];
  assign _01_[14] = en ? (* src = "dff.v:18" *) d_in[14] : mux_out[14];
  assign _01_[15] = en ? (* src = "dff.v:18" *) d_in[15] : mux_out[15];
  assign _00_[0] = reset ? (* src = "dff.v:14" *) starting[0] : _01_[0];
  assign _00_[1] = reset ? (* src = "dff.v:14" *) starting[1] : _01_[1];
  assign _00_[2] = reset ? (* src = "dff.v:14" *) starting[2] : _01_[2];
  assign _00_[3] = reset ? (* src = "dff.v:14" *) starting[3] : _01_[3];
  assign _00_[4] = reset ? (* src = "dff.v:14" *) starting[4] : _01_[4];
  assign _00_[5] = reset ? (* src = "dff.v:14" *) starting[5] : _01_[5];
  assign _00_[6] = reset ? (* src = "dff.v:14" *) starting[6] : _01_[6];
  assign _00_[7] = reset ? (* src = "dff.v:14" *) starting[7] : _01_[7];
  assign _00_[8] = reset ? (* src = "dff.v:14" *) starting[8] : _01_[8];
  assign _00_[9] = reset ? (* src = "dff.v:14" *) starting[9] : _01_[9];
  assign _00_[10] = reset ? (* src = "dff.v:14" *) starting[10] : _01_[10];
  assign _00_[11] = reset ? (* src = "dff.v:14" *) starting[11] : _01_[11];
  assign _00_[12] = reset ? (* src = "dff.v:14" *) starting[12] : _01_[12];
  assign _00_[13] = reset ? (* src = "dff.v:14" *) starting[13] : _01_[13];
  assign _00_[14] = reset ? (* src = "dff.v:14" *) starting[14] : _01_[14];
  assign _00_[15] = reset ? (* src = "dff.v:14" *) starting[15] : _01_[15];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[12] <= _00_[12];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[13] <= _00_[13];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[14] <= _00_[14];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[15] <= _00_[15];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[0] <= _00_[0];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[1] <= _00_[1];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[2] <= _00_[2];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[3] <= _00_[3];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[4] <= _00_[4];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[5] <= _00_[5];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[6] <= _00_[6];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[7] <= _00_[7];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[8] <= _00_[8];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[9] <= _00_[9];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[10] <= _00_[10];
  (* src = "dff.v:13" *)
  always @(posedge clk)
      mux_out[11] <= _00_[11];
endmodule
